-- Seeds the pomeon database with initial data

INSERT INTO pokemon
    (pokemon_name, pokemon_height,
     pokemon_weight, pokemon_description)
VALUES
	('Bulbasaur', 70, 6900, 'For some time after its birth, it grows by gaining nourishment from the seed on its back.'),
	('Ivysaur', 50, 13000, 'When the bud on its back starts swelling, a sweet aroma wafts to indicate the flower’s coming bloom.'),
	('Venusaur', 500, 100000, 'After a rainy day, the flower on its back smells stronger. The scent attracts other Pokémon.'),
	('Charmander', 60, 8500, 'The fire on the tip of its tail is a measure of its life. If healthy, its tail burns intensely.'),
	('Charmeleon', 110, 19000, 'In the rocky mountains where Charmeleon live, their fiery tails shine at night like stars.'),
	('Charizard', 170, 90500, 'It is said that Charizard’s fire burns hotter if it has experienced harsh battles.'),
	('Squirtle', 50, 9000, 'It shelters itself in its shell then strikes back with spouts of water at every opportunity.'),
	('Wartortle', 100, 22500, 'It is said to live 10,000 years. Its furry tail is popular as a symbol of longevity.'),
	('Blastoise', 160, 85500, 'The jets of water it spouts from the rocket cannons on its shell can punch through thick steel.'),
	('Caterpie', 30, 2900, 'It releases a stench from its red antenna to repel enemies. It grows by molting repeatedly.'),
	('Metapod', 70, 9900, 'A steel-hard shell protects its tender body. It quietly endures hardships while awaiting evolution.'),
	('Butterfree', 110, 32000, 'It loves the honey of flowers and can locate flower patches that have even tiny amounts of pollen.'),
	('Weedle', 30, 3200, 'It eats its weight in leaves every day. It fends off attackers with the needle on its head.'),
	('Kakuna', 60, 10000, 'While awaiting evolution, it hides from predators under leaves and in nooks of branches.'),
	('Beedrill', 100, 29500, 'Its best attack involves flying around at high speed, striking with poison needles, then flying off.'),
	('Pidgey', 30, 1800, 'It is docile and prefers to avoid conflict. If disturbed, however, it can ferociously strike back.'),
	('Pidgeotto', 110, 30000, 'It flies over its wide territory in search of prey, downing it with its highly developed claws.'),
	('Pidgeot', 150, 39500, 'By flapping its wings with all its might, Pidgeot can make a gust of wind capable of bending tall trees.'),
	('Rattata', 30, 3500, 'It searches for food all day. It gnaws on hard objects to wear down its fangs, which grow constantly during its lifetime.'),
	('Raticate', 70, 18500, 'With its long fangs, this surprisingly violent Pokémon can gnaw away even thick concrete with ease.'),
	('Spearow', 30, 2000, 'It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.'),
	('Fearow', 120, 38000, 'It has the stamina to fly all day on its broad wings. It fights by using its sharp beak.'),
	('Ekans', 200, 6900, 'It sneaks through grass without making a sound and strikes unsuspecting prey from behind.'),
	('Arbok', 350, 65000, 'The pattern on its belly is for intimidation. It constricts foes while they are frozen in fear.'),
	('Pikachu', 40, 6000, 'It occasionally uses an electric shock to recharge a fellow Pikachu that is in a weakened state.'),
	('Raichu', 80, 30000, 'Its tail discharges electricity into the ground, protecting it from getting shocked.'),
	('Sandshrew', 60, 12000, 'It digs deep burrows to live in. When in danger, it rolls up its body to withstand attacks.'),
	('Sandslash', 100, 29500, 'The spikes on its body are made up of its hardened hide. It rolls up and attacks foes with its spikes.'),
	('Nidoran♀', 40, 7000, 'While it does not prefer to fight, even one drop of the poison it secretes from barbs can be fatal.'),
	('Nidorina', 80, 20000, 'When it senses danger, it raises all the barbs on its body. These barbs grow slower than Nidorino’s.'),
	('Nidoqueen', 130, 60000, 'Its entire body is armored with hard scales. It will protect the young in its burrow with its life.'),
	('Nidoran♂', 50, 9000, 'It scans its surroundings by raising its ears out of the grass. Its toxic horn is for protection.'),
	('Nidorino', 90, 19500, 'It has a violent disposition and stabs foes with its horn, which oozes poison upon impact.'),
	('Nidoking', 140, 62000, 'One swing of its mighty tail can snap a telephone pole as if it were a matchstick.'),
	('Clefairy', 60, 7500, 'On nights with a full moon, Clefairy gather from all over and dance. Bathing in moonlight makes them float.'),
	('Clefable', 130, 40000, 'Their ears are sensitive enough to hear a pin drop from over a mile away, so they’re usually found in quiet places.'),
	('Vulpix', 60, 9900, 'As each tail grows, its fur becomes more lustrous. When held, it feels slightly warm.'),
	('Ninetales', 110, 19900, 'Each of its nine tails is imbued with supernatural power, and it can live for a thousand years.'),
	('Jigglypuff', 50, 5500, 'Looking into its cute, round eyes makes it start singing a song so pleasant listeners can’t help but fall asleep.'),
	('Wigglytuff', 100, 12000, 'Its fine fur feels so pleasant, those who accidentally touch it cannot take their hands away.'),
	('Zubat', 80, 7500, 'It does not need eyes, because it emits ultrasonic waves to check its surroundings while it flies.'),
	('Golbat', 160, 55000, 'Flitting around in the dead of night, it sinks its fangs into its prey and drains a nearly fatal amount of blood.'),
	('Oddish', 50, 5400, 'It often plants its root feet in the ground during the day and sows seeds as it walks about at night.'),
	('Gloom', 80, 8600, 'The honey it drools from its mouth smells so atrocious, it can curl noses more than a mile away.'),
	('Vileplume', 120, 18600, 'Its petals are the largest in the world. As it walks, it scatters extremely allergenic pollen.'),
	('Paras', 30, 5400, 'Mushrooms named tochukaso grow on its back. They grow along with the host Paras.'),
	('Parasect', 100, 29500, 'A mushroom grown larger than the host’s body controls Parasect. It scatters poisonous spores.'),
	('Venonat', 100, 30000, 'Its big eyes are actually clusters of tiny eyes. At night, its kind is drawn by light.'),
	('Venomoth', 150, 12500, 'It flutters its wings to scatter dustlike scales. The scales leach toxins if they contact skin.'),
	('Diglett', 20, 800, 'A Pokémon that lives underground. Because of its dark habitat, it is repelled by bright sunlight.'),
	('Dugtrio', 70, 33300, 'Its three heads move alternately, driving it through tough soil to depths of over 60 miles.'),
	('Meowth', 40, 4200, 'It is nocturnal in nature. If it spots something shiny, its eyes glitter brightly.'),
	('Persian', 100, 32000, 'A very haughty Pokémon. Among fans, the size of the jewel in its forehead is a topic of much talk.'),
	('Psyduck', 80, 19600, 'When headaches stimulate its brain cells, which are usually inactive, it can use a mysterious power.'),
	('Golduck', 170, 76600, 'When its forehead shines mysteriously, Golduck can use the full extent of its power.'),
	('Mankey', 50, 28000, 'It lives in treetop colonies. If one becomes enraged, the whole colony rampages for no reason.'),
	('Primeape', 100, 32000, 'It grows angry if you see its eyes and gets angrier if you run. If you beat it, it gets even madder.'),
	('Growlithe', 70, 19000, 'Extremely loyal to its Trainer, it will bark at those who approach the Trainer unexpectedly and run them out of town.'),
	('Arcanine', 190, 155000, 'The sight of it running over 6,200 miles in a single day and night has captivated many people.'),
	('Poliwag', 60, 12400, 'Its skin is so thin, its internal organs are visible. It has trouble walking on its newly grown feet.'),
	('Poliwhirl', 100, 20000, 'The spiral pattern on its belly subtly undulates. Staring at it gradually causes drowsiness.'),
	('Poliwrath', 130, 54000, 'With its extremely tough muscles, it can keep swimming in the Pacific Ocean without resting.'),
	('Abra', 90, 19500, 'Using its psychic power is such a strain on its brain that it needs to sleep for 18 hours a day.'),
	('Kadabra', 130, 56500, 'It stares at its silver spoon to focus its mind. It emits more alpha waves while doing so.'),
	('Alakazam', 150, 48000, 'The spoons clutched in its hands are said to have been created by its psychic powers.'),
	('Machop', 80, 19500, 'Though small in stature, it is powerful enough to easily heft and throw a number of Geodude at once.'),
	('Machoke', 150, 70500, 'It happily carries heavy cargo to toughen up. It willingly does hard work for people.'),
	('Machamp', 160, 130000, 'Its four muscled arms slam foes with powerful punches and chops at blinding speed.'),
	('Bellsprout', 70, 4000, 'It prefers hot and humid environments. It is quick at capturing prey with its vines.'),
	('Weepinbell', 100, 6400, 'A Pokémon that appears to be a plant. It captures unwary prey by dousing them with a toxic powder.'),
	('Victreebel', 170, 15500, 'It pools in its mouth a fluid with a honey-like scent, which is really an acid that dissolves anything.'),
	('Tentacool', 90, 45500, 'Because its body is almost entirely composed of water, it shrivels up if it is washed ashore.'),
	('Tentacruel', 160, 55000, 'It extends its 80 tentacles to form an encircling poisonous net that is difficult to escape.'),
	('Geodude', 40, 20000, 'At rest, it looks just like a rock. Carelessly stepping on it will make it swing its fists angrily.'),
	('Graveler', 100, 105000, 'It rolls on mountain paths to move. Once it builds momentum, no Pokémon can stop it without difficulty.'),
	('Golem', 140, 300000, 'Even dynamite can’t harm its hard, boulder-like body. It sheds its hide just once a year.'),
	('Ponyta', 100, 30000, 'As a newborn, it can barely stand. However, through galloping, its legs are made tougher and faster.'),
	('Rapidash', 170, 95000, 'When at an all-out gallop, its blazing mane sparkles, enhancing its beautiful appearance.'),
	('Slowpoke', 120, 36000, 'Although slow, it is skilled at fishing with its tail. It does not feel pain if its tail is bitten.'),
	('Slowbro', 160, 78500, 'Though usually dim witted, it seems to become inspired if the Shellder on its tail bites down.'),
	('Magnemite', 30, 6000, 'The electromagnetic waves emitted by the units at the sides of its head expel antigravity, which allows it to float.'),
	('Magneton', 100, 60000, 'The stronger electromagnetic waves from the three linked Magnemite are enough to dry out surrounding moisture.'),
	('Farfetch’d', 80, 15000, 'It can’t live without the stalk it holds. That’s why it defends the stalk from attackers with its life.'),
	('Doduo', 140, 39200, 'The brains in its two heads appear to communicate emotions to each other with a telepathic power.'),
	('Dodrio', 180, 85200, 'When Doduo evolves into this odd breed, one of its heads splits into two. It runs at nearly 40 mph.'),
	('Seel', 110, 90000, 'The colder it gets, the better it feels. It joyfully swims around oceans so cold that they are filled with floating ice.'),
	('Dewgong', 170, 120000, 'Its streamlined body has low resistance, and it swims around cold oceans at a speed of eight knots.'),
	('Grimer', 90, 30000, 'Born from sludge, these Pokémon now gather in polluted places and increase the bacteria in their bodies.'),
	('Muk', 120, 30000, 'It’s so stinky! Muk’s body contains toxic elements, and any plant will wilt when it passes by.'),
	('Shellder', 30, 4000, 'It swims backward by opening and closing its two shells. Its large tongue is always kept hanging out.'),
	('Cloyster', 150, 132500, 'It fights by keeping its shell tightly shut for protection and by shooting spikes to repel foes.'),
	('Gastly', 130, 100, 'Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.'),
	('Haunter', 160, 100, 'It likes to lurk in the dark and tap shoulders with a gaseous hand. Its touch causes endless shuddering.'),
	('Gengar', 150, 40500, 'The leer that floats in darkness belongs to a Gengar delighting in casting curses on people.'),
	('Onix', 880, 210000, 'Opening its large mouth, it ingests massive amounts of soil and creates long tunnels.'),
	('Drowzee', 100, 32400, 'It can tell what people are dreaming by sniffing with its big nose. It loves fun dreams.'),
	('Hypno', 160, 75600, 'Seeing its swinging pendulum can induce sleep in three seconds, even in someone who just woke up.'),
	('Krabby', 40, 6500, 'It lives in burrows dug on sandy beaches. Its pincers fully grow back if they are broken in battle.'),
	('Kingler', 130, 60000, 'The larger pincer has 10,000- horsepower strength. However, it is so heavy, it is difficult to aim.'),
	('Voltorb', 50, 10400, 'It looks just like a Poké Ball. It is dangerous because it may electrocute or explode on contact.'),
	('Electrode', 120, 66600, 'It is known to drift on winds if it is bloated to bursting with stored electricity.'),
	('Exeggcute', 40, 2500, 'Its six eggs converse using telepathy. They can quickly gather if they become separated.'),
	('Exeggutor', 200, 120000, 'It is called “The Walking Jungle.” If a head grows too big, it falls off and becomes an Exeggcute.'),
	('Cubone', 40, 6500, 'When it thinks of its dead mother, it cries. Its crying makes the skull it wears rattle hollowly.'),
	('Marowak', 100, 45000, 'From its birth, this savage Pokémon constantly holds bones. It is skilled in using them as weapons.'),
	('Hitmonlee', 150, 49800, 'Its legs can stretch double. First-time foes are startled by its extensible reach.'),
	('Hitmonchan', 140, 50200, 'The arm-twisting punches it throws pulverize even concrete. It rests after three minutes of fighting.'),
	('Lickitung', 120, 65500, 'Being licked by its long, saliva-covered tongue leaves a tingling sensation. Extending its tongue retracts its tail.'),
	('Koffing', 60, 1000, 'Toxic gas is held within its thin, balloon-shaped body, so it can cause massive explosions.'),
	('Weezing', 120, 9500, 'Inhaling toxic fumes from trash and mixing them inside its body lets it spread an even fouler stench.'),
	('Rhyhorn', 100, 115000, 'Its powerful tackles can destroy anything. However, it is too slow witted to help people work.'),
	('Rhydon', 190, 120000, 'Standing on its hind legs freed its forelegs and made it smarter. It is very forgetful, however.'),
	('Chansey', 110, 34600, 'A kindly Pokémon that lays highly nutritious eggs and shares them with injured Pokémon or people.'),
	('Tangela', 100, 35000, 'Many writhing vines cover it, so its true identity remains unknown. The blue vines grow its whole life long.'),
	('Kangaskhan', 220, 80000, 'It raises its offspring in its belly pouch. It lets the baby out to play only when it feels safe.'),
	('Horsea', 40, 8000, 'It makes its nest in the shade of corals. If it senses danger, it spits murky ink and flees.'),
	('Seadra', 120, 25000, 'Its spines provide protection. Its fins and bones are prized as traditional-medicine ingredients.'),
	('Goldeen', 60, 15000, 'Though it appears very elegant when swimming with fins unfurled, it can jab powerfully with its horn.'),
	('Seaking', 130, 39000, 'In autumn, its body becomes more fatty in preparing to propose to a mate. It takes on beautiful colors.'),
	('Staryu', 80, 34500, 'As long as its red core remains, it can regenerate its body instantly, even if it’s torn apart.'),
	('Starmie', 110, 80000, 'Its core shines in many colors and sends radio signals into space to communicate with something.'),
	('Mr. Mime', 130, 54500, 'It shapes an invisible wall in midair by minutely vibrating its fingertips to stop molecules in the air.'),
	('Scyther', 150, 56000, 'The sharp scythes on its forearms become increasingly sharp by cutting through hard objects.'),
	('Jynx', 140, 40600, 'Its cries sound like human speech. However, it is impossible to tell what it is trying to say.'),
	('Electabuzz', 110, 30000, 'Research is progressing on storing lightning in Electabuzz so this energy can be used at any time.'),
	('Magmar', 130, 44500, 'The scorching fire exhaled by Magmar forms heat waves around its body, making it hard to see the Pokémon clearly.'),
	('Pinsir', 150, 55000, 'It grips prey with its powerful pincers and will not let go until the prey is torn in half.'),
	('Tauros', 140, 88400, 'Once it takes aim at its foe, it makes a headlong charge. It is famous for its violent nature.'),
	('Magikarp', 90, 10000, 'A Magikarp living for many years can leap a mountain using Splash. The move remains useless, though.'),
	('Gyarados', 650, 235000, 'Once it begins to rampage, a Gyarados will burn everything down, even in a harsh storm.'),
	('Lapras', 250, 220000, 'Able to understand human speech and very intelligent, it loves to swim in the sea with people on its back.'),
	('Ditto', 30, 4000, 'It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.'),
	('Eevee', 30, 6500, 'Thanks to its unstable genetic makeup, this special Pokémon conceals many different possible evolutions.'),
	('Vaporeon', 100, 29000, 'Its cell composition is similar to water molecules. As a result, it can’t be seen when it melts away into water.'),
	('Jolteon', 80, 24500, 'By storing electricity in its body, it can shoot its bristlelike fur like a barrage of missiles.'),
	('Flareon', 90, 25000, 'Inhaled air is carried to its flame sac, heated, and exhaled as fire that reaches over 3,000 degrees F.'),
	('Porygon', 80, 36500, 'A man-made Pokémon created using advanced scientific means. It can move freely in cyberspace.'),
	('Omanyte', 40, 7500, 'A Pokémon that was resurrected from a fossil using modern science. It swam in ancient seas.'),
	('Omastar', 100, 35000, 'It is thought that this Pokémon became extinct because its spiral shell grew too large.'),
	('Kabuto', 50, 11500, 'It is thought to have inhabited beaches 300 million years ago. It is protected by a stiff shell.'),
	('Kabutops', 130, 40500, 'It is thought that this Pokémon came onto land because its prey adapted to life on land.'),
	('Aerodactyl', 180, 59000, 'A Pokémon that roamed the skies in the dinosaur era. Its teeth are like saw blades.'),
	('Snorlax', 210, 460000, 'When its belly is full, it becomes too lethargic to even lift a finger, so it is safe to bounce on its belly.'),
	('Articuno', 170, 55400, 'A legendary bird Pokémon. It can create blizzards by freezing moisture in the air.'),
	('Zapdos', 160, 52600, 'A legendary Pokémon that is said to live in thunderclouds. It freely controls lightning bolts.'),
	('Moltres', 200, 60000, 'One of the legendary bird Pokémon. It is said that its appearance indicates the coming of spring.'),
	('Dratini', 180, 3300, 'It is called the “Mirage Pokémon” because so few have seen it. Its shed skin has been found.'),
	('Dragonair', 400, 16500, 'If its body takes on an aura, the weather changes instantly. It is said to live in seas and lakes.'),
	('Dragonite', 220, 210000, 'It is said to make its home somewhere in the sea. It guides crews of shipwrecks to shore.'),
	('Mewtwo', 200, 122000, 'A Pokémon created by recombining Mew’s genes. It’s said to have the most savage heart among Pokémon.'),
	('Mew', 40, 4000, 'Because it can use all kinds of moves, many scientists believe Mew to be the ancestor of Pokémon.'),
	('Chikorita', 90, 6400, 'It uses the leaf on its head to determine the temperature and humidity. It loves to sunbathe.'),
	('Bayleef', 120, 15800, 'The buds that ring its neck give off a spicy aroma that perks people up.'),
	('Meganium', 180, 100500, 'Its breath has the fantastic ability to revive dead plants and flowers.'),
	('Cyndaquil', 50, 7900, 'It has a timid nature. If it is startled, the flames on its back burn more vigorously.'),
	('Quilava', 90, 19000, 'It intimidates foes with the heat of its flames. The fire burns more strongly when it readies to fight.'),
	('Typhlosion', 170, 79500, 'It attacks using blasts of fire. It creates heat shimmers with intense fire to hide itself.'),
	('Totodile', 60, 9500, 'It has the habit of biting anything with its developed jaws. Even its Trainer needs to be careful.'),
	('Croconaw', 110, 25000, 'Once it bites down, it won’t let go until it loses its fangs. New fangs quickly grow into place.'),
	('Feraligatr', 230, 88800, 'It usually moves slowly, but it goes at blinding speed when it attacks and bites prey.'),
	('Sentret', 80, 6000, 'It has a very nervous nature. It stands up high on its tail so it can scan wide areas.'),
	('Furret', 180, 32500, 'The mother puts its offspring to sleep by curling up around them. It corners foes with speed.'),
	('Hoothoot', 70, 21200, 'It marks time precisely. Some countries consider it to be a wise friend, versed in the world’s ways.'),
	('Noctowl', 160, 40800, 'Its eyes are specially developed to enable it to see clearly even in murky darkness and minimal light.'),
	('Ledyba', 100, 10800, 'It is so timid, it can’t move if it isn’t with a swarm of others. It conveys its feelings with scent.'),
	('Ledian', 140, 35600, 'It uses starlight as energy. When more stars appear at night, the patterns on its back grow larger.'),
	('Spinarak', 50, 8500, 'It sets a trap by spinning a web with thin but strong silk. It waits motionlessly for prey to arrive.'),
	('Ariados', 110, 33500, 'It attaches silk to its prey and sets it free. Later, it tracks the silk to the prey and its friends.'),
	('Crobat', 180, 75000, 'Having four wings allows it to fly more quickly and quietly so it can sneak up on prey without its noticing.'),
	('Chinchou', 50, 12000, 'It discharges positive and negative electricity from its antenna tips to shock its foes.'),
	('Lanturn', 120, 22500, 'Lanturn’s light can shine up from great depths. It is nicknamed “The Deep-Sea Star.”'),
	('Pichu', 30, 2000, 'The electric sacs in its cheeks are small. If even a little electricity leaks, it becomes shocked.'),
	('Cleffa', 30, 3000, 'According to local rumors, Cleffa are often seen in places where shooting stars have fallen.'),
	('Igglybuff', 30, 1000, 'Its body has a faintly sweet scent and is bouncy and soft. If it bounces even once, it cannot stop.'),
	('Togepi', 30, 1500, 'It transforms the kindness and joy of others into happiness, which it stores in its shell.'),
	('Togetic', 60, 3200, 'To share its happiness, it flies around the world seeking kind- hearted people.'),
	('Natu', 20, 2000, 'It picks food from cactus plants, deftly avoiding buds and spines. It seems to skip about to move.'),
	('Xatu', 150, 15000, 'This odd Pokémon can see both the past and the future. It eyes the sun’s movement all day.'),
	('Mareep', 60, 7800, 'When cold weather increases static electricity, its wool doubles in size and the tip of its tail glows slightly.'),
	('Flaaffy', 80, 13300, 'Not even downy wool will grow on its rubbery, nonconductive patches of skin that prevent electrical shock.'),
	('Ampharos', 140, 61500, 'The tip of its tail shines so brightly it can be used to send sea-navigation beacons to distant foreign shores.'),
	('Bellossom', 40, 5800, 'When the heavy rainfall season ends, it is drawn out by warm sunlight to dance in the open.'),
	('Marill', 40, 8500, 'The oil-filled tail functions as a buoy, so it’s fine even in rivers with strong currents.'),
	('Azumarill', 80, 28500, 'Its long ears are superb sensors. It can distinguish the movements of things in water and tell what they are.'),
	('Sudowoodo', 120, 38000, 'To avoid being attacked, it does nothing but mimic a tree. It hates water and flees from rain.'),
	('Politoed', 110, 33900, 'It gathers groups of others as their leader. Its cries make Poliwag obey.'),
	('Hoppip', 40, 500, 'It drifts on winds. It is said that when Hoppip gather in fields and mountains, spring is on the way.'),
	('Skiploom', 60, 1000, 'It blooms when the weather warms. It floats in the sky to soak up as much sunlight as possible.'),
	('Jumpluff', 80, 3000, 'Blown by seasonal winds, it circles the globe, scattering cotton spores as it goes.'),
	('Aipom', 80, 11500, 'It lives high among the treetops. It can use its tail as freely and cleverly as its hands.'),
	('Sunkern', 30, 1800, 'It suddenly falls out of the sky in the morning. Knowing it’s weak, it simply feeds until it evolves.'),
	('Sunflora', 80, 8500, 'Since it converts sunlight into energy, it is always looking in the direction of the sun.'),
	('Yanma', 120, 38000, 'By flapping its wings at high speed, it can fly freely through the air. Even sudden stops are no problem.'),
	('Wooper', 40, 8500, 'When walking on land, it covers its body with a poisonous film that keeps its skin from dehydrating.'),
	('Quagsire', 140, 75000, 'It has an easygoing nature. It doesn’t care if it bumps its head on boats and boulders while swimming.'),
	('Espeon', 90, 26500, 'Its fur is so sensitive, it can feel minute shifts in the air and predict the weather...and its foes’ thoughts.'),
	('Umbreon', 100, 27000, 'When exposed to the moon’s aura, the rings on its body glow faintly and it’s filled with a mysterious power.'),
	('Murkrow', 50, 2100, 'If spotted, it will lure an unwary person into chasing it then lose the pursuer on mountain trails.'),
	('Slowking', 200, 79500, 'Being bitten by Shellder gave it intelligence comparable to that of award-winning scientists.'),
	('Misdreavus', 70, 1000, 'A Pokémon that startles people in the middle of the night. It gathers fear as its energy.'),
	('Unown', 50, 5000, 'When alone, nothing happens. However, if there are two or more, an odd power is said to emerge.'),
	('Wobbuffet', 130, 28500, 'It desperately tries to keep its black tail hidden. It is said to be proof the tail hides a secret.'),
	('Girafarig', 150, 41500, 'The head on its tail contains a small brain. It can instinctively fight even while facing backward.'),
	('Pineco', 60, 7200, 'It looks just like a pinecone. Its shell protects it from bird Pokémon that peck it by mistake.'),
	('Forretress', 120, 125800, 'It is encased in a steel shell. Its peering eyes are all that can be seen of its mysterious innards.'),
	('Dunsparce', 150, 14000, 'It creates mazes in dark locations. When spotted, it flees into the ground by digging with its tail.'),
	('Gligar', 110, 64800, 'It clamps on to its chosen prey then jabs the stinger on its tail into the prey while it’s stunned with surprise.'),
	('Steelix', 920, 400000, 'The iron it ingested with the soil it swallowed transformed its body and made it harder than diamonds.'),
	('Snubbull', 60, 7800, 'Small Pokémon flee from its scary face. It is, however, considered by women to be cute.'),
	('Granbull', 140, 48700, 'It is timid in spite of its looks. If it becomes enraged, however, it will strike with its huge fangs.'),
	('Qwilfish', 50, 3900, 'It shoots the poison spines on its body in all directions. Its round form makes it a poor swimmer.'),
	('Scizor', 180, 118000, 'It raises its pincers with eyelike markings for intimidation. It also swings them down dangerously.'),
	('Shuckle', 60, 20500, 'The berries stored in its vaselike shell eventually become a thick, pulpy juice.'),
	('Heracross', 150, 54000, 'No matter how heavy its opponents, it flings them far away with its prized horn.'),
	('Sneasel', 90, 28000, 'A smart and sneaky Pokémon, it makes its opponents flinch by suddenly showing the claws hidden in its paws.'),
	('Teddiursa', 60, 8800, 'It lets honey soak into its paws so it can lick them all the time. Every set of paws tastes unique.'),
	('Ursaring', 180, 125800, 'In its territory, it leaves scratches on trees that bear delicious berries or fruits.'),
	('Slugma', 70, 35000, 'Its body is made of magma. If it doesn’t keep moving, its body will cool and harden.'),
	('Magcargo', 80, 55000, 'Its body temperature is roughly 18,000 degrees F. Flames spout from gaps in its hardened shell.'),
	('Swinub', 40, 6500, 'Rooting the tip of its snout into the ground, it searches for food. Sometimes it even digs up a hot spring.'),
	('Piloswine', 110, 55800, 'With its excellent sense of smell, it’s even able to find mushrooms that are buried under frozen ground.'),
	('Corsola', 60, 5000, 'They prefer unpolluted southern seas. Their coral branches lose their color and deteriorate in dirty water.'),
	('Remoraid', 60, 12000, 'The water they shoot from their mouths can hit moving prey from more than 300 feet away.'),
	('Octillery', 90, 28500, 'It has a tendency to want to be in holes. It prefers rock crags or pots and sprays ink from them before attacking.'),
	('Delibird', 90, 16000, 'It carries food all day long. When someone is lost in the mountains, it shares that food.'),
	('Mantine', 210, 220000, 'If it builds up enough speed swimming, it can fly over 300 feet out of the water from the surface of the ocean.'),
	('Skarmory', 170, 50500, 'Its heavy-looking iron body is actually thin and light, so it can fly at speeds over 180 mph.'),
	('Houndour', 60, 10800, 'It is smart enough to hunt in packs. It uses a variety of cries for communicating with others.'),
	('Houndoom', 140, 35000, 'The flames it breathes when angry contain toxins. If they cause a burn, it will hurt forever.'),
	('Kingdra', 180, 152000, 'It lives in caves on the seafloor and creates giant whirlpools every time it moves.'),
	('Phanpy', 50, 33500, 'It is strong despite its compact size. It can easily pick up and carry an adult human on its back.'),
	('Donphan', 110, 120000, 'It attacks by curling up then rolling into its foe. It can blow apart a house in one hit.'),
	('Porygon2', 60, 32500, 'It was upgraded to enable the exploration of other planets. However, it failed to measure up.'),
	('Stantler', 140, 71200, 'Staring at its antlers creates an odd sensation as if one were being drawn into their centers.'),
	('Smeargle', 120, 58000, 'It marks its territory by using its tail like a paintbrush. There are more than 5,000 different marks.'),
	('Tyrogue', 70, 21000, 'It is famous for its eagerness to fight and always nurses injuries from challenging larger foes.'),
	('Hitmontop', 140, 48000, 'It fights while spinning like a top. The centrifugal force boosts its destructive power by 10.'),
	('Smoochum', 40, 6000, 'It tests everything by touching with its lips, which remember what it likes and dislikes.'),
	('Elekid', 60, 23500, 'Spinning its arms around to generate electricity makes the area between its horns shine light blue.'),
	('Magby', 70, 21400, 'It’s small, but its body temperature is over 1,100 degrees F. Embers escape its mouth and nose when it breathes.'),
	('Miltank', 120, 75500, 'It is said that kids who drink Miltank’s milk grow up to become hearty, healthy adults.'),
	('Blissey', 150, 46800, 'The eggs it lays are filled with happiness. Eating even one bite will bring a smile to anyone.'),
	('Raikou', 190, 178000, 'It is said to have fallen with lightning. It can fire thunderbolts from the rain clouds on its back.'),
	('Entei', 210, 198000, 'It is said that when it roars, a volcano erupts somewhere around the globe.'),
	('Suicune', 200, 187000, 'It races around the world to purify fouled water. It dashes away with the north wind.'),
	('Larvitar', 60, 72000, 'Born deep underground, it comes aboveground and becomes a pupa once it has finished eating the surrounding soil.'),
	('Pupitar', 120, 152000, 'This pupa flies around wildly by venting with great force the gas pressurized inside its body.'),
	('Tyranitar', 200, 202000, 'The quakes caused when it walks make even great mountains crumble and change the surrounding terrain.'),
	('Lugia', 520, 216000, 'It sleeps in a deep-sea trench. If it flaps its wings, it is said to cause a 40-day storm.'),
	('Ho-Oh', 380, 199000, 'Its feathers are in seven colors. It is said that anyone seeing it is promised eternal happiness.'),
	('Celebi', 60, 5000, 'It has the power to travel across time, but it is said to appear only in peaceful times.'),
	('Treecko', 50, 5000, 'The soles of its feet are covered by countless tiny spikes, enabling it to walk on walls and ceilings.'),
	('Grovyle', 90, 21600, 'It lives in dense jungles. While closing in on its prey, it leaps from branch to branch.'),
	('Sceptile', 170, 52200, 'The leaves that grow on its arms can slice down thick trees. It is without peer in jungle combat.'),
	('Torchic', 40, 2500, 'A fire burns inside, so it feels very warm to hug. It launches fireballs of 1,800 degrees F.'),
	('Combusken', 90, 19500, 'Its kicking mastery lets it loose 10 kicks per second. It emits sharp cries to intimidate foes.'),
	('Blaziken', 190, 52000, 'Flames spout from its wrists, enveloping its knuckles. Its punches scorch its foes.'),
	('Mudkip', 40, 7600, 'To alert it, the fin on its head senses the flow of water. It has the strength to heft boulders.'),
	('Marshtomp', 70, 28000, 'Its sturdy legs give it sure footing, even in mud. It burrows into dirt to sleep.'),
	('Swampert', 150, 81900, 'It can swim while towing a large ship. It bashes down foes with a swing of its thick arms.'),
	('Poochyena', 50, 13600, 'A Pokémon with a persistent nature, it chases its chosen prey until the prey becomes exhausted.'),
	('Mightyena', 100, 37000, 'It chases down prey in a pack. It will never disobey the commands of a skilled Trainer.'),
	('Zigzagoon', 40, 17500, 'It walks in zigzag fashion. It is good at finding items in the grass and even in the ground.'),
	('Linoone', 50, 32500, 'It charges prey at speeds over 60 mph. However, because it can only run straight, it often fails.'),
	('Wurmple', 30, 3600, 'Often targeted by bird Pokémon, it desperately resists by releasing poison from its tail spikes.'),
	('Silcoon', 60, 10000, 'It wraps silk around the branches of a tree. It drinks rainwater on its silk while awaiting evolution.'),
	('Beautifly', 100, 28400, 'Despite its looks, it is aggressive. It jabs with its long, thin mouth if disturbed while collecting pollen.'),
	('Cascoon', 70, 11500, 'It never forgets any attack it endured while in the cocoon. After evolution, it seeks payback.'),
	('Dustox', 120, 31600, 'Toxic powder is scattered with each flap. At night, it is known to strip leaves off trees lining boulevards.'),
	('Lotad', 50, 2600, 'It looks like an aquatic plant and serves as a ferry to Pokémon that can’t swim.'),
	('Lombre', 120, 32500, 'It has a mischievous spirit. If it spots an angler, it will tug on the fishing line to interfere.'),
	('Ludicolo', 150, 55000, 'If it hears festive music, all its muscles fill with energy. It can’t help breaking out into a dance.'),
	('Seedot', 50, 4000, 'When it dangles from a tree branch, it looks just like an acorn. It enjoys scaring other Pokémon.'),
	('Nuzleaf', 100, 28000, 'The sound of its grass flute makes its listeners uneasy. It lives deep in forests.'),
	('Shiftry', 130, 59600, 'By flapping its leafy fan, it can whip up gusts of 100 ft/second that can level houses.'),
	('Taillow', 30, 2300, 'It has a gutsy spirit that makes it bravely take on tough foes. It flies in search of warm climates.'),
	('Swellow', 70, 19800, 'It circles the sky in search of prey. When it spots one, it dives steeply to catch the prey.'),
	('Wingull', 60, 9500, 'It makes its nest on sheer cliffs. Riding the sea breeze, it glides up into the expansive skies.'),
	('Pelipper', 120, 28000, 'Skimming the water’s surface, it dips its large bill in the sea, scoops up food and water, and carries it.'),
	('Ralts', 40, 6600, 'If its horns capture the warm feelings of people or Pokémon, its body warms up slightly.'),
	('Kirlia', 80, 20200, 'If its Trainer becomes happy, it overflows with energy, dancing joyously while spinning about.'),
	('Gardevoir', 160, 48400, 'To protect its Trainer, it will expend all its psychic power to create a small black hole.'),
	('Surskit', 50, 1700, 'It appears as if it is skating on water. It draws prey with a sweet scent from the tip of its head.'),
	('Masquerain', 80, 3600, 'Its antennae have eye patterns on them. Its four wings enable it to hover and fly in any direction.'),
	('Shroomish', 40, 4500, 'It spouts poison spores from the top of its head. These spores cause pain all over if inhaled.'),
	('Breloom', 120, 39200, 'Its short arms stretch when it throws punches. Its technique is equal to that of pro boxers.'),
	('Slakoth', 80, 24000, 'If it eats just three leaves in a day, it is satisfied. Other than that, it sleeps for 20 hours a day.'),
	('Vigoroth', 140, 46500, 'Its heartbeat is fast and its blood so agitated that it can’t sit still for one second.'),
	('Slaking', 200, 130500, 'This Pokémon lives lying on its side. It only rolls over and moves when there is no more grass to eat.'),
	('Nincada', 50, 5500, 'It grows underground, sensing its surroundings using antennae instead of its virtually blind eyes.'),
	('Ninjask', 80, 12000, 'Because it moves so quickly, it sometimes becomes unseeable. It congregates around tree sap.'),
	('Shedinja', 80, 1200, 'A discarded bug shell that came to life. Peering into the crack on its back is said to steal one’s spirit.'),
	('Whismur', 60, 16300, 'Usually, its cries are like quiet murmurs. If frightened, it shrieks at the same volume as a jet plane.'),
	('Loudred', 100, 40500, 'The shock waves from its cries can tip over trucks. It stamps its feet to power up.'),
	('Exploud', 150, 84000, 'Its howls can be heard over six miles away. It emits all sorts of noises from the ports on its body.'),
	('Makuhita', 100, 86400, 'It toughens its body by slamming into thick trees. Many snapped trees can be found near its nest.'),
	('Hariyama', 230, 253800, 'It loves to match power with big-bodied Pokémon. It can knock a truck flying with its arm thrusts.'),
	('Azurill', 20, 2000, 'It swings its large, nutrient-filled tail around to fight opponents bigger than itself.'),
	('Nosepass', 100, 97000, 'Its magnetic nose always faces north and draws iron objects to its body to protect itself better.'),
	('Skitty', 60, 11000, 'It shows its cute side by chasing its own tail until it gets dizzy.'),
	('Delcatty', 110, 32600, 'The reason it does not have a nest is that it simply searches for a clean, comfortable place then sleeps there.'),
	('Sableye', 50, 11000, 'It hides in the darkness of caves. Its diet of gems has transformed its eyes into gemstones.'),
	('Mawile', 60, 11500, 'Attached to its head is a huge set of jaws formed by horns. It can chew through iron beams.'),
	('Aron', 40, 60000, 'In order to build up its steel body, it eats iron ore. This pesky Pokémon is known to eat railroad tracks.'),
	('Lairon', 90, 120000, 'Lairon fight over territory, and when their steel bodies collide, sparks fly.'),
	('Aggron', 210, 360000, 'It claims an entire mountain as its own. The more wounds it has, the more it has battled, so don’t take it lightly.'),
	('Meditite', 60, 11200, 'It always trains deep in mountains. It levitates when it heightens its spiritual power through meditation.'),
	('Medicham', 130, 31500, 'It gains the ability to see the aura of its opponents by honing its mind through starvation.'),
	('Electrike', 60, 15200, 'Using electricity stored in its fur, it stimulates its muscles to heighten its reaction speed.'),
	('Manectric', 150, 40200, 'It discharges electricity from its mane. It creates a thundercloud overhead to drop lightning bolts.'),
	('Plusle', 40, 4200, 'It cheers on friends with pom-poms made of sparks. It drains power from telephone poles.'),
	('Minun', 40, 4200, 'It cheers on friends. If its friends are losing, its body lets off more and more sparks.'),
	('Volbeat', 70, 17700, 'It communicates with others by lighting up its rear at night. It loves Illumise’s sweet aroma.'),
	('Illumise', 60, 17700, 'With its sweet aroma, it guides Volbeat to draw signs with light in the night sky.'),
	('Roselia', 30, 2000, 'It uses the different poisons in each hand separately when it attacks. The stronger its aroma, the healthier it is.'),
	('Gulpin', 40, 10300, 'Almost all its body is its stomach. Its harsh digestive juices quickly dissolve anything it swallows.'),
	('Swalot', 170, 80000, 'It swallows anything whole. It sweats toxic fluids from its follicles to douse foes.'),
	('Carvanha', 80, 20800, 'They swarm any foe that invades their territory. Their sharp fangs can tear out boat hulls.'),
	('Sharpedo', 180, 88800, 'Its fangs rip through sheet iron. It swims at 75 mph and is known as “The Bully of the Sea.”'),
	('Wailmer', 200, 130000, 'It eats one ton of food every day. It plays by shooting stored seawater out its blowholes with great force.'),
	('Wailord', 1450, 398000, 'It can sometimes knock out opponents with the shock created by breaching and crashing its big body onto the water.'),
	('Numel', 70, 24000, 'The magma in its body reaches 2,200 degrees F. Its hump gets smaller when it uses Fire-type moves.'),
	('Camerupt', 190, 220000, 'The volcanoes on its back have a major eruption every 10 years--or whenever it becomes really angry.'),
	('Torkoal', 50, 80400, 'It burns coal inside its shell for energy. It blows out black soot if it is endangered.'),
	('Spoink', 70, 30600, 'Using its tail like a spring, it keeps its heart beating by bouncing constantly. If it stops, it dies.'),
	('Grumpig', 90, 71500, 'It uses black pearls to amplify its psychic power. It does a strange dance to control foes’ minds.'),
	('Spinda', 110, 5000, 'No two Spinda have the same pattern of spots. Its tottering step fouls the aim of foes.'),
	('Trapinch', 70, 15000, 'It makes an inescapable conical pit and lies in wait at the bottom for prey to come tumbling down.'),
	('Vibrava', 110, 15300, 'The ultrasonic waves it generates by rubbing its two wings together cause severe headaches.'),
	('Flygon', 200, 82000, 'Known as “The Desert Spirit,” this Pokémon hides in the sandstorms it causes by beating its wings.'),
	('Cacnea', 40, 51300, 'By storing water in its body, this desert dweller can survive for 30 days without water.'),
	('Cacturne', 130, 77400, 'It becomes active at night, seeking prey that is exhausted from the day’s desert heat.'),
	('Swablu', 40, 1200, 'For some reason, it likes to land on people’s heads softly and act like it’s a hat.'),
	('Altaria', 110, 20600, 'On sunny days, it flies freely through the sky and blends into the clouds. It sings in a beautiful soprano.'),
	('Zangoose', 130, 40300, 'It’s Seviper’s archrival. To threaten those it encounters, it fans out the claws on its front paws.'),
	('Seviper', 270, 52500, 'Constant polishing makes the edge of the blade on its tail extremely sharp. It’s Zangoose’s archrival.'),
	('Lunatone', 100, 168000, 'The phase of the moon apparently has some effect on its power. It’s active on the night of a full moon.'),
	('Solrock', 120, 154000, 'Solar energy is the source of its power, so it is strong during the daytime. When it spins, its body shines.'),
	('Barboach', 40, 1900, 'Its slimy body is hard to grasp. In one region, it is said to have been born from hardened mud.'),
	('Whiscash', 90, 23600, 'It is extremely protective of its territory. If any foe approaches, it attacks using vicious tremors.'),
	('Corphish', 60, 11500, 'No matter how dirty the water in the river, it will adapt and thrive. It has a strong will to survive.'),
	('Crawdaunt', 110, 32800, 'Loving to battle, this Pokémon pinches all Pokémon that enter its territory with its pincers and throws them out.'),
	('Baltoy', 50, 21500, 'Discovered in ancient ruins, it moves by spinning around and forms a group when it finds others.'),
	('Claydol', 150, 108000, 'This mysterious Pokémon started life as an ancient clay figurine made over 20,000 years ago.'),
	('Lileep', 100, 23800, 'It lived on the seafloor 100 million years ago and was reanimated scientifically.'),
	('Cradily', 150, 60400, 'It lives in the shallows of warm seas. When the tide goes out, it digs up prey from beaches.'),
	('Anorith', 70, 12500, 'A Pokémon ancestor that was reanimated from a fossil. It lived in the sea and hunted with claws.'),
	('Armaldo', 150, 68200, 'It went ashore after evolving. Its entire body is clad in a sturdy armor.'),
	('Feebas', 60, 7400, 'It is a shabby and ugly Pokémon. However, it is very hardy and can survive on little water.'),
	('Milotic', 620, 162000, 'Its lovely scales are described as rainbow colored. They change color depending on the viewing angle.'),
	('Castform', 30, 800, 'Temperature and weather affect its cellular structure, so this Pokémon changes form according to the weather.'),
	('Kecleon', 100, 22000, 'It can freely change its body’s color. The zigzag pattern on its belly doesn’t change, however.'),
	('Shuppet', 60, 2300, 'It feeds on the dark emotions of sadness and hatred, which make it grow steadily stronger.'),
	('Banette', 110, 12500, 'A doll that became a Pokémon over its grudge of being thrown away. It seeks the child who disowned it.'),
	('Duskull', 80, 15000, 'It loves the crying of children. It startles bad kids by passing through walls and making them cry.'),
	('Dusclops', 160, 30600, 'It seeks drifting will-o’-the-wisps and sucks them into its empty body. What happens inside is a mystery.'),
	('Tropius', 200, 100000, 'It flies by flapping its broad leaves and gives the sweet, delicious fruit around its neck to children.'),
	('Chimecho', 60, 1000, 'Its cries echo inside its hollow body to emerge as beautiful notes for startling and repelling foes.'),
	('Absol', 120, 47000, 'It appears from deep in the mountains to warn people about upcoming disasters it has sensed with its horn.'),
	('Wynaut', 60, 14000, 'It grows strong by pushing up against others en masse. It loves eating sweet fruit.'),
	('Snorunt', 70, 16800, 'It is said that several Snorunt gather under giant leaves and live together in harmony.'),
	('Glalie', 150, 256500, 'It prevents prey from escaping by instantaneously freezing moisture in the air.'),
	('Spheal', 80, 39500, 'They can’t swim well yet, and they move much faster by rolling. When they’re happy, they clap fins.'),
	('Sealeo', 110, 87600, 'Be it Spheal or Poké Ball, it will spin any round object on its nose with the greatest of ease.'),
	('Walrein', 140, 150600, 'Not only does its thick blubber keep it warm, it also protects it from attacks. It shatters ice with its prized tusks.'),
	('Clamperl', 40, 52500, 'It makes a single pearl during its lifetime. The pearl is said to amplify psychic power.'),
	('Huntail', 170, 27000, 'It lives deep in the sea. With a tail shaped like a small fish, it attracts unsuspecting prey.'),
	('Gorebyss', 180, 22600, 'It lives at the bottom of the sea. In the springtime, its pink body turns more vivid for some reason.'),
	('Relicanth', 100, 23400, 'A rare Pokémon discovered during a deep-sea exploration. It has not changed in over 100 million years.'),
	('Luvdisc', 60, 8700, 'It lives in warm seas. It is said that a couple finding this Pokémon will be blessed with eternal love.'),
	('Bagon', 60, 42100, 'Dreaming of one day flying, it practices by leaping off cliffs every day.'),
	('Shelgon', 110, 110500, 'Within its rugged shell, its cells have begun changing. The shell peels off the instant it evolves.'),
	('Salamence', 150, 102600, 'As a result of its long-held dream of flying, its cellular structure changed, and wings grew out.'),
	('Beldum', 60, 95200, 'Its cells are all magnetic, and it communicates with others by using magnetic pulses.'),
	('Metang', 120, 202500, 'It is formed by two Beldum joining together. Its two brains are linked, amplifying its psychic power.'),
	('Metagross', 160, 550000, 'With four linked brains, it’s more intelligent than a supercomputer, and it uses calculations to analyze foes.'),
	('Regirock', 170, 230000, 'Its entire body is made of rock. If any part chips off in battle, it attaches rocks to repair itself.'),
	('Regice', 180, 175000, 'Its body is made of ice from the ice age. It controls frigid air of -328 degrees Fahrenheit.'),
	('Registeel', 190, 205000, 'Tempered by pressure underground over tens of thousands of years, its body cannot be scratched.'),
	('Latias', 140, 40000, 'Its body is covered with a down that can refract light in such a way that it becomes invisible.'),
	('Latios', 200, 60000, 'A highly intelligent Pokémon. By folding back its wings in flight, it can overtake jet planes.'),
	('Kyogre', 450, 352000, 'It is said to have widened the seas by causing downpours. It had been asleep in a marine trench.'),
	('Groudon', 350, 950000, 'It had been asleep in underground magma ever since it fiercely fought Kyogre long ago.'),
	('Rayquaza', 700, 206500, 'It lives in the ozone layer far above the clouds and cannot be seen from the ground.'),
	('Jirachi', 30, 1100, 'It is said to have the ability to grant any wish for just one week every thousand years.'),
	('Deoxys', 170, 60800, 'An alien virus that fell to earth on a meteor underwent a DNA mutation to become this Pokémon.'),
	('Turtwig', 40, 10200, 'The shell on its back is made of soil. On a very healthy Turtwig, the shell should feel moist.'),
	('Grotle', 110, 97000, 'It knows where pure water wells up. It carries fellow Pokémon there on its back.'),
	('Torterra', 220, 310000, 'Some Pokémon are born on a Torterra’s back and spend their entire life there.'),
	('Chimchar', 50, 6200, 'It is very agile. Before going to sleep, it extinguishes the flame on its tail to prevent fires.'),
	('Monferno', 90, 22000, 'It skillfully controls the intensity of the fire on its tail to keep its foes at an ideal distance.'),
	('Infernape', 120, 55000, 'It uses unique fighting moves with fire on its hands and feet. It will take on any opponent.'),
	('Piplup', 40, 5200, 'A poor walker, it often falls down. However, its strong pride makes it puff up its chest without a care.'),
	('Prinplup', 80, 23000, 'Because every Prinplup considers itself to be the most important, they can never form a group.'),
	('Empoleon', 170, 84500, 'If anyone were to hurt its pride, it would slash them with wings that can cleave through an ice floe.'),
	('Starly', 30, 2000, 'Because they are weak individually, they form groups. However, they bicker if the group grows too big.'),
	('Staravia', 60, 15500, 'Recognizing their own weakness, they always live in a group. When alone, a Staravia cries noisily.'),
	('Staraptor', 120, 24900, 'It never stops attacking even if it is injured. It fusses over the shape of its comb.'),
	('Bidoof', 50, 20000, 'A comparison revealed that Bidoof’s front teeth grow at the same rate as Rattata’s.'),
	('Bibarel', 100, 31500, 'A river dammed by Bibarel will never overflow its banks, which is appreciated by people nearby.'),
	('Kricketot', 30, 2200, 'Its legs are short. Whenever it stumbles, its stiff antennae clack with a xylophone-like sound.'),
	('Kricketune', 100, 25500, 'There is a village that hosts a contest based on the amazingly variable cries of this Pokémon.'),
	('Shinx', 50, 9500, 'The extension and contraction of its muscles generates electricity. It glows when in trouble.'),
	('Luxio', 90, 30500, 'Strong electricity courses through the tips of its sharp claws. A light scratch causes fainting in foes.'),
	('Luxray', 140, 42000, 'It can see clearly through walls to track down its prey and seek its lost young.'),
	('Budew', 20, 1200, 'Sensitive to changing temperatures, the bud blooms when it’s warm, releasing toxic pollen.'),
	('Roserade', 90, 14500, 'Luring prey with a sweet scent, it uses poison whips on its arms to poison, bind, and finish off the prey.'),
	('Cranidos', 90, 31500, 'A lifelong jungle dweller from 100 million years ago, it would snap obstructing trees with head butts.'),
	('Rampardos', 160, 102500, 'If two were to smash their heads together, their foot-thick skulls would keep them from fainting.'),
	('Shieldon', 50, 57000, 'It is outstandingly armored. As a result, it can eat grass and berries without having to fight.'),
	('Bastiodon', 130, 149500, 'When they lined up side by side, no foe could break through. They shielded their young in that way.'),
	('Burmy', 20, 3400, 'Even if it is born where there are no cocooning materials, it somehow always ends up with a cloak.'),
	('Wormadam', 50, 6500, 'When evolving, its body takes in surrounding materials. As a result, there are many body variations.'),
	('Mothim', 90, 23300, 'While it loves floral honey, it won’t gather any itself. Instead, it plots to steal some from Combee.'),
	('Combee', 30, 5500, 'This Pokémon is a set of three. When they sleep, they gather up and form a giant hive of 100 Combee.'),
	('Vespiquen', 120, 38500, 'It houses its colony in cells in its body and releases various pheromones to make those grubs do its bidding.'),
	('Pachirisu', 40, 3900, 'A pair may be seen rubbing their cheek pouches together in an effort to share stored electricity.'),
	('Buizel', 70, 29500, 'It inflates the flotation sac around its neck and pokes its head out of the water to see what is going on.'),
	('Floatzel', 110, 33500, 'It is a common sight around fishing ports. It is known to rescue people and carry off prey.'),
	('Cherubi', 40, 3300, 'The small ball is not only filled with nutrients, it is also tasty. Starly try to peck it off.'),
	('Cherrim', 50, 9300, 'If it senses strong sunlight, it opens its folded petals to absorb the sun’s rays with its whole body.'),
	('Shellos', 30, 6300, 'Beware of pushing strongly on its squishy body, as it makes a mysterious purple fluid ooze out.'),
	('Gastrodon', 90, 29900, 'Long ago, its entire back was shielded with a sturdy shell. There are traces of it left in its cells.'),
	('Ambipom', 120, 20300, 'Split into two, the tails are so adept at handling and doing things, Ambipom rarely uses its hands.'),
	('Drifloon', 40, 1200, 'These Pokémon are called the “Signpost for Wandering Spirits.” Children holding them sometimes vanish.'),
	('Drifblim', 120, 15000, 'They carry people and Pokémon, but the wind can catch them, so there can’t be a fixed destination.'),
	('Buneary', 40, 5500, 'By extending its rolled-up ears and striking the ground, it can bound so high it surprises itself.'),
	('Lopunny', 120, 33300, 'Extremely cautious, it quickly bounds off when it senses danger.'),
	('Mismagius', 90, 4400, 'Its cry sounds like an incantation. It is said the cry may rarely be imbued with happiness-giving power.'),
	('Honchkrow', 90, 27300, 'If one utters a deep cry, many Murkrow gather quickly. For this, it is called “Summoner of Night.”'),
	('Glameow', 50, 3900, 'It hides its spiteful tendency of hooking its claws into the nose of its Trainer if it isn’t fed.'),
	('Purugly', 100, 43800, 'It binds its body with its tails to make itself look bigger. If it locks eyes, it will glare ceaselessly.'),
	('Chingling', 20, 600, 'There is an orb inside its mouth. When it hops, the orb bounces all over and makes a ringing sound.'),
	('Stunky', 40, 19200, 'It sprays a foul fluid from its rear. Its stench spreads over a mile radius, driving Pokémon away.'),
	('Skuntank', 100, 38000, 'It attacks by spraying a horribly smelly fluid from the tip of its tail. Attacks from above confound it.'),
	('Bronzor', 50, 60500, 'They are found in ancient tombs. The patterns on their backs are said to be imbued with mysterious power.'),
	('Bronzong', 130, 187000, 'In ages past, this Pokémon was revered as a bringer of rain. It was found buried in the ground.'),
	('Bonsly', 50, 15000, 'It prefers an arid atmosphere. It leaks water that looks like tears when adjusting its moisture level.'),
	('Mime Jr.', 60, 13000, 'It mimics the expressions and motions of those it sees to understand the feelings of others.'),
	('Happiny', 60, 24400, 'It likes to carry around a small rock. It may wander around others’ feet and cause them to stumble.'),
	('Chatot', 50, 1900, 'Its tongue is just like a human’s. As a result, it can cleverly mimic human speech.'),
	('Spiritomb', 100, 108000, 'Its constant mischief and misdeeds resulted in it being bound to an Odd Keystone by a mysterious spell.'),
	('Gible', 70, 20500, 'It attacks using its huge mouth. While its attacks are powerful, it hurts itself out of clumsiness, too.'),
	('Gabite', 140, 56000, 'It loves sparkly things. It seeks treasures in caves and hoards the loot in its nest.'),
	('Garchomp', 190, 95000, 'It is said that when one runs at high speed, its wings create blades of wind that can fell nearby trees.'),
	('Munchlax', 60, 105000, 'In its desperation to gulp down food, it forgets about the food it has hidden under its fur.'),
	('Riolu', 70, 20200, 'It uses the shapes of auras, which change according to emotion, to communicate with others.'),
	('Lucario', 120, 54000, 'By reading the auras of all things, it can tell how others are feeling from over half a mile away.'),
	('Hippopotas', 80, 49500, 'It shuts its nostrils tight then travels through sand as if walking. They form colonies of around 10.'),
	('Hippowdon', 200, 300000, 'It is surprisingly quick to anger. It holds its mouth agape as a display of its strength.'),
	('Skorupi', 80, 12000, 'It lives in arid regions and can go without food for a year while waiting for prey.'),
	('Drapion', 130, 61500, 'It takes pride in its strength. Even though it can tear foes apart, it finishes them off with powerful poison.'),
	('Croagunk', 70, 23000, 'Inflating its poison sacs, it fills the area with an odd sound and hits flinching opponents with a poison jab.'),
	('Toxicroak', 130, 44400, 'The croaking that Toxicroak produces before a battle is for churning the poison it has stored in its poison sac.'),
	('Carnivine', 140, 27000, 'Using its tentacles to lash itself to trees, it lies in wait for prey, luring it close with sweet-smelling drool.'),
	('Finneon', 40, 7000, 'The line running down its side can store sunlight. It shines vividly at night.'),
	('Lumineon', 120, 24000, 'It crawls along the seafloor using its long front fins like legs. It competes for food with Lanturn.'),
	('Mantyke', 100, 65000, 'The pattern on its back varies by region. It often swims in a school of Remoraid.'),
	('Snover', 100, 50500, 'Seemingly curious about people, they gather around footsteps they find on snowy mountains.'),
	('Abomasnow', 220, 135500, 'They appear when the snow flowers bloom. When the petals fall, they retreat to places unknown again.'),
	('Weavile', 110, 34000, 'They communicate by clawing signs in boulders and work together to surround enemies.'),
	('Magnezone', 120, 180000, 'Sometimes the magnetism emitted by Magnezone is too strong, making them attract each other so they cannot move.'),
	('Lickilicky', 170, 140000, 'Their saliva contains lots of components that can dissolve anything. The numbness caused by their lick does not dissipate.'),
	('Rhyperior', 240, 282800, 'It can launch a rock held in its hand like a missile by tightening then expanding muscles instantly.'),
	('Tangrowth', 200, 128600, 'Even if one of its arms is eaten, it’s fine. The Pokémon regenerates quickly and will go right back to normal.'),
	('Electivire', 180, 138600, 'The instant it presses the tips of its tails onto an opponent, it sends over 20,000 volts of electricity into the foe.'),
	('Magmortar', 160, 68000, 'When shooting 3,600 degree F fireballs from its arms, its body takes on a whitish hue from the intense heat.'),
	('Togekiss', 150, 38000, 'It shares many blessings with people who respect one another’s rights and avoid needless strife.'),
	('Yanmega', 190, 51500, 'It prefers to battle by biting apart foes’ heads instantly while flying by at high speed.'),
	('Leafeon', 100, 25500, 'With cells similar to those of plants, it performs photosynthesis inside its body and creates pure air.'),
	('Glaceon', 80, 25900, 'It lowers its body heat to freeze its fur. The hairs then become like needles it can fire.'),
	('Gliscor', 200, 42500, 'It dances silently through the sky. When it approaches prey, it can land a critical hit in an instant.'),
	('Mamoswine', 250, 291000, 'When the temperature rose at the end of the ice age, most Mamoswine disappeared.'),
	('Porygon-Z', 90, 34000, 'Its programming was modified to enable work in alien dimensions. It did not work as planned.'),
	('Gallade', 160, 52000, 'When trying to protect someone, it extends its elbows as if they were swords and fights savagely.'),
	('Probopass', 140, 340000, 'It freely controls three units called Mini-Noses using magnetic force.'),
	('Dusknoir', 220, 106600, 'It is said to take lost spirits into its pliant body and guide them home.'),
	('Froslass', 130, 26600, 'It freezes prey by blowing its -58 degrees F breath. It is said to then secretly display its prey.'),
	('Rotom', 30, 300, 'Its electric-like body can enter some kinds of machines and take control in order to make mischief.'),
	('Uxie', 30, 300, 'When Uxie flew, people gained the ability to solve problems. It was the birth of knowledge.'),
	('Mesprit', 30, 300, 'When Mesprit flew, people learned the joy and sadness of living. It was the birth of emotions.'),
	('Azelf', 30, 300, 'When Azelf flew, people gained the determination to do things. It was the birth of willpower.'),
	('Dialga', 540, 683000, 'A legendary Pokémon of Sinnoh. It is said that time flows when Dialga’s heart beats.'),
	('Palkia', 420, 336000, 'A legendary Pokémon of Sinnoh. It is said that space becomes more stable with Palkia’s every breath.'),
	('Heatran', 170, 430000, 'Its body is made of rugged steel. However, it is partially melted in spots because of its own heat.'),
	('Regigigas', 370, 420000, 'It is said to have made Pokémon that look like itself from a special ice mountain, rocks, and magma.'),
	('Giratina', 450, 750000, 'It was banished for its violence. It silently gazed upon the old world from the Distortion World.'),
	('Cresselia', 150, 85600, 'On nights around the quarter moon, the aurora from its tail extends and undulates beautifully.'),
	('Phione', 40, 3100, 'It drifts in warm seas. It always returns to where it was born, no matter how far it may have drifted.'),
	('Manaphy', 30, 1400, 'It is born with a wondrous power that lets it bond with any kind of Pokémon.'),
	('Darkrai', 150, 50500, 'To protect itself, it afflicts those around it with nightmares. However, it means no harm.'),
	('Shaymin', 20, 2100, 'The flowers all over its body burst into bloom if it is lovingly hugged and senses gratitude.'),
	('Arceus', 320, 320000, 'It is said to have emerged from an egg in a place where there was nothing then shaped the world.'),
	('Victini', 40, 4000, 'When it shares the infinite energy it creates, that being’s entire body will be overflowing with power.'),
	('Snivy', 60, 8100, 'Being exposed to sunlight makes its movements swifter. It uses vines more adeptly than its hands.'),
	('Servine', 80, 16000, 'When it gets dirty, its leaves can’t be used in photosynthesis, so it always keeps itself clean.'),
	('Serperior', 330, 63000, 'It only gives its all against strong opponents who are not fazed by the glare from Serperior’s noble eyes.'),
	('Tepig', 50, 9900, 'It loves to eat roasted berries, but sometimes it gets too excited and burns them to a crisp.'),
	('Pignite', 100, 55500, 'The more it eats, the more fuel it has to make the fire in its stomach stronger. This fills it with even more power.'),
	('Emboar', 160, 150000, 'A flaring beard of fire is proof that it is fired up. It is adept at using many different moves.'),
	('Oshawott', 50, 5900, 'The scalchop on its stomach isn’t just used for battle--it can be used to break open hard berries as well.'),
	('Dewott', 80, 24500, 'As a result of strict training, each Dewott learns different forms for using the scalchops.'),
	('Samurott', 150, 94600, 'In the time it takes a foe to blink, it can draw and sheathe the seamitars attached to its front legs.'),
	('Patrat', 50, 11600, 'Extremely cautious, one of them will always be on the lookout, but it won’t notice a foe coming from behind.'),
	('Watchog', 110, 27000, 'Using luminescent matter, it makes its eyes and body glow and stuns attacking opponents.'),
	('Lillipup', 40, 4100, 'Though it is a very brave Pokémon, it’s also smart enough to check its foe’s strength and avoid battle.'),
	('Herdier', 90, 14700, 'This very loyal Pokémon helps Trainers, and it also takes care of other Pokémon.'),
	('Stoutland', 120, 61000, 'Being wrapped in its long fur is so comfortable that a person would be fine even overnight on a wintry mountain.'),
	('Purrloin', 40, 10100, 'Their cute act is a ruse. They trick people and steal their valuables just to see the looks on their faces.'),
	('Liepard', 110, 37500, 'Their beautiful form comes from the muscles they have developed. They run silently in the night.'),
	('Pansage', 60, 10500, 'It’s good at finding berries and gathers them from all over. It’s kind enough to share them with friends.'),
	('Simisage', 110, 30500, 'It strikes its enemies with a thorn-covered tail. The leaf on its head is bitter.'),
	('Pansear', 60, 11000, 'Very intelligent, it roasts berries before eating them. It likes to help people.'),
	('Simisear', 100, 28000, 'When it gets excited, embers rise from its head and tail and it gets hot. For some reason, it loves sweets.'),
	('Panpour', 60, 13500, 'The water stored inside the tuft on its head is full of nutrients. It waters plants with it using its tail.'),
	('Simipour', 100, 29000, 'It prefers places with clean water. When its tuft runs low, it replenishes it by siphoning up water with its tail.'),
	('Munna', 60, 23300, 'This Pokémon appears before people and Pokémon who are having nightmares and eats those dreams.'),
	('Musharna', 110, 60500, 'The dream mist coming from its forehead changes into many different colors depending on the dream that was eaten.'),
	('Pidove', 30, 2100, 'This very forgetful Pokémon will wait for a new order from its Trainer even though it already has one.'),
	('Tranquill', 60, 15000, 'No matter where in the world it goes, it knows where its nest is, so it never gets separated from its Trainer.'),
	('Unfezant', 120, 29000, 'Males swing the plumage on their heads to threaten others, but females are better at flying.'),
	('Blitzle', 80, 29800, 'Its mane shines when it discharges electricity. They use the frequency and rhythm of these flashes to communicate.'),
	('Zebstrika', 160, 79500, 'When this ill-tempered Pokémon runs wild, it shoots lightning from its mane in all directions.'),
	('Roggenrola', 40, 18000, 'The hexagonal-shaped hole is its ear. It has a tendency to walk in the direction the sound is coming from.'),
	('Boldore', 90, 102000, 'When it is healthy, its core sticks out. Always facing the same way, it swiftly moves front to back and left to right.'),
	('Gigalith', 170, 260000, 'The solar rays it absorbs are processed in its energy core and fired as a ball of light.'),
	('Woobat', 40, 2100, 'The heart-shaped mark left on a body after a Woobat has been attached to it is said to bring good fortune.'),
	('Swoobat', 90, 10500, 'It shakes its tail vigorously when it emits ultrasonic waves strong enough to reduce concrete to rubble.'),
	('Drilbur', 30, 8500, 'By spinning its body, it can dig straight through the ground at a speed of 30 mph.'),
	('Excadrill', 70, 40400, 'Forming a drill with its steel claws and head, it can bore through a steel plate, no matter how thick it is.'),
	('Audino', 110, 31000, 'Using the feelers on its ears, it can tell how someone is feeling or when an egg might hatch.'),
	('Timburr', 60, 12500, 'Always carrying squared logs, they help out with construction. As they grow, they carry bigger logs.'),
	('Gurdurr', 120, 40000, 'With strengthened bodies, they skillfully wield steel beams to take down buildings.'),
	('Conkeldurr', 140, 87000, 'Rather than rely on force, they master moves that utilize the centrifugal force of spinning concrete.'),
	('Tympole', 50, 4500, 'By vibrating its cheeks, it emits sound waves imperceptible to humans and warns others of danger.'),
	('Palpitoad', 80, 17000, 'It lives in the water and on land. It uses its long, sticky tongue to immobilize its opponents.'),
	('Seismitoad', 150, 62000, 'By putting power into its bumps, it creates vibrations and increases the power of its punches.'),
	('Throh', 130, 55500, 'When it encounters a foe bigger than itself, it wants to throw it. It changes belts as it gets stronger.'),
	('Sawk', 140, 51000, 'Desiring the strongest karate chop, they seclude themselves in mountains and train without sleeping.'),
	('Sewaddle', 30, 2500, 'Since this Pokémon makes its own clothes out of leaves, it is a popular mascot for fashion designers.'),
	('Swadloon', 50, 7300, 'Preferring dark, damp places, it spends the entire day eating fallen leaves that lie around it.'),
	('Leavanny', 120, 20500, 'Upon finding a small Pokémon, it weaves clothing for it from leaves by using the sticky silk secreted from its mouth.'),
	('Venipede', 40, 5300, 'Using the feelers on its head and tail, it picks up vibrations in the air to determine its prey’s location and state.'),
	('Whirlipede', 120, 58500, 'Storing energy for evolution, it sits. But, when predators approach, it moves to stab them with poison spikes.'),
	('Scolipede', 250, 200500, 'It clasps its prey with the claws on its neck until it stops moving. Then it finishes it off with deadly poison.'),
	('Cottonee', 30, 600, 'Perhaps because they feel more at ease in a group, they stick to others they find. They end up looking like a cloud.'),
	('Whimsicott', 70, 6600, 'They appear along with whirlwinds. They pull pranks, such as moving furniture and leaving balls of cotton in homes.'),
	('Petilil', 50, 6600, 'The leaves on its head grow right back even if they fall out. These bitter leaves refresh those who eat them.'),
	('Lilligant', 110, 16300, 'The fragrance of the garland on its head has a relaxing effect, but taking care of it is very difficult.'),
	('Basculin', 100, 18000, 'Red- and blue-striped Basculin are very violent and always fighting. They are also remarkably tasty.'),
	('Sandile', 70, 15200, 'They live hidden under hot desert sands in order to keep their body temperature from dropping.'),
	('Krokorok', 100, 33400, 'Protected by thin membranes, their eyes can see even in the dead of night. They live in groups of a few individuals.'),
	('Krookodile', 150, 96300, 'Very violent Pokémon, they try to clamp down on anything that moves in front of their eyes.'),
	('Darumaka', 60, 37500, 'When it sleeps, it pulls its limbs into its body and its internal fire goes down to 1,100° F.'),
	('Darmanitan', 130, 92900, 'When one is injured in a fierce battle, it hardens into a stone-like form. Then it meditates and sharpens its mind.'),
	('Maractus', 100, 28000, 'When it moves rhythmically, it makes a sound similar to maracas, making the surprised Pokémon flee.'),
	('Dwebble', 30, 14500, 'When it finds a stone of a suitable size, it secretes a liquid from its mouth to open up a hole to crawl into.'),
	('Crustle', 140, 200000, 'When its boulder is broken in battles for territory, it feels unsure and begins to weaken.'),
	('Scraggy', 60, 11800, 'Proud of its sturdy skull, it suddenly headbutts everything, but its weight makes it unstable, too.'),
	('Scrafty', 110, 30000, 'It pulls up its shed skin to protect itself while it kicks. The bigger the crest, the more respected it is.'),
	('Sigilyph', 140, 14000, 'The guardians of an ancient city, they always fly the same route while keeping watch for invaders.'),
	('Yamask', 50, 1500, 'These Pokémon arose from the spirits of people interred in graves. Each retains memories of its former life.'),
	('Cofagrigus', 170, 76500, 'Grave robbers who mistake them for real coffins and get too close end up trapped inside their bodies.'),
	('Tirtouga', 70, 16500, 'This Pokémon was restored from a fossil. It swam skillfully and dove to depths beyond half a mile.'),
	('Carracosta', 120, 81000, 'It could knock out a foe with a slap from one of its developed front appendages and chew it up, shell or bones and all.'),
	('Archen', 50, 9500, 'It was revived from an ancient fossil. Not able to fly, it lived in treetops and hopped from one branch to another.'),
	('Archeops', 140, 32000, 'It runs better than it flies. It takes off into the sky by running at a speed of 25 mph.'),
	('Trubbish', 60, 31000, 'Wanting more garbage, they follow people who litter. They always belch poison gas.'),
	('Garbodor', 190, 107300, 'Consuming garbage makes new kinds of poison gases and liquids inside their bodies.'),
	('Zorua', 70, 12500, 'It changes so it looks just like its foe, tricks it, and then uses that opportunity to flee.'),
	('Zoroark', 160, 81100, 'Stories say those who tried to catch Zoroark were trapped in an illusion and punished.'),
	('Minccino', 40, 5800, 'Minccino greet each other by grooming one another thoroughly with their tails.'),
	('Cinccino', 50, 7500, 'Cinccino’s body is coated in a special oil that helps it deflect attacks, such as punches.'),
	('Gothita', 40, 5800, 'It stares intently at everything. It can become so obsessed with watching that it doesn’t notice attacks.'),
	('Gothorita', 70, 18000, 'According to many old tales, it creates friends for itself by controlling sleeping children on starry nights.'),
	('Gothitelle', 150, 44000, 'It can see the future from the movement of the stars. When it learns its Trainer’s life span, it cries in sadness.'),
	('Solosis', 30, 1000, 'Because their bodies are enveloped in a special liquid, they are fine in any environment, no matter how severe.'),
	('Duosion', 60, 8000, 'When their two divided brains think the same thoughts, their psychic power is maximized.'),
	('Reuniclus', 100, 20100, 'They use psychic power to control their arms, which are made of a special liquid. They can crush boulders psychically.'),
	('Ducklett', 50, 5500, 'They are better at swimming than flying, and they happily eat their favorite food, peat moss, as they dive underwater.'),
	('Swanna', 130, 24200, 'Despite their elegant appearance, they can flap their wings strongly and fly for thousands of miles.'),
	('Vanillite', 40, 5700, 'Theoretically, this Pokémon formed from icicles bathed in energy from the morning sun. Their breath is -58° F.'),
	('Vanillish', 110, 41000, 'They cool down the surrounding air and create ice particles, which they use to freeze their foes.'),
	('Vanilluxe', 130, 57500, 'Swallowing large amounts of water, they make snow clouds inside their bodies and, when angry, cause violent blizzards.'),
	('Deerling', 60, 19500, 'Their coloring changes according to the seasons and can be slightly affected by the temperature and humidity as well.'),
	('Sawsbuck', 190, 92500, 'They migrate according to the seasons, so some people call Sawsbuck the harbingers of spring.'),
	('Emolga', 40, 5000, 'It glides on its outstretched membrane while shocking foes with the electricity stored in the pouches on its cheeks.'),
	('Karrablast', 50, 5900, 'For some reason they evolve when they receive electrical energy while they are attacking Shelmet.'),
	('Escavalier', 100, 33000, 'Wearing the shell covering they stole from Shelmet, they defend themselves and attack with two lances.'),
	('Foongus', 20, 1000, 'It lures Pokémon with its pattern that looks just like a Poké Ball then releases poison spores.'),
	('Amoonguss', 60, 10500, 'It moves the caps on both arms and does a dance to lure prey. It prefers damp places.'),
	('Frillish', 120, 33000, 'If its veil-like arms stun and wrap a foe, that foe will be dragged miles below the surface, never to return.'),
	('Jellicent', 220, 135000, 'Its body is mostly seawater. It’s said there’s a castle of ships Jellicent have sunk on the seafloor.'),
	('Alomomola', 120, 31600, 'It gently holds injured and weak Pokémon in its fins. Its special membrane heals their wounds.'),
	('Joltik', 10, 600, 'Since it can’t generate its own electricity, it sticks onto large-bodied Pokémon and absorbs static electricity.'),
	('Galvantula', 80, 14300, 'It creates barriers from electrified silk that stun foes. This works as a weapon as well as a defense.'),
	('Ferroseed', 60, 18800, 'It absorbs the iron it finds in the rock while clinging to the ceiling. It shoots spikes when in danger.'),
	('Ferrothorn', 100, 110000, 'By swinging around its three spiky feelers and shooting spikes, it can obliterate an opponent.'),
	('Klink', 30, 21000, 'Two bodies comprise a fixed pair. They spin around each other to generate energy.'),
	('Klang', 60, 51000, 'A minigear and big gear comprise its body. If the minigear it launches at a foe doesn’t return, it will die.'),
	('Klinklang', 60, 81000, 'The minigear spins at high speed. Then the energy from the red core charges the minigear to make it ready to fire.'),
	('Tynamo', 20, 300, 'One alone can emit only a trickle of electricity, so a group of them gathers to unleash a powerful electric shock.'),
	('Eelektrik', 120, 22000, 'It wraps itself around its prey and paralyzes it with electricity from the round spots on its sides. Then it chomps.'),
	('Eelektross', 210, 80500, 'It latches on to prey with its sucker mouth, sinking in its fangs and shocking the prey with powerful electricity.'),
	('Elgyem', 50, 9000, 'Rumors of its origin are linked to a UFO crash site in the desert 50 years ago.'),
	('Beheeyem', 100, 34500, 'Apparently, it communicates by flashing its three fingers, but those patterns haven’t been decoded.'),
	('Litwick', 30, 3100, 'Its flame is usually out, but it starts shining when it absorbs life force from people or Pokémon.'),
	('Lampent', 60, 13000, 'The spirits it absorbs fuel its baleful fire. It hangs around hospitals waiting for people to pass on.'),
	('Chandelure', 100, 34300, 'The spirits burned up in its ominous flame lose their way and wander this world forever.'),
	('Axew', 60, 18000, 'Its large tusks have a tendency to break, but each time they grow back, they grow in harder and sturdier.'),
	('Fraxure', 100, 36000, 'A broken tusk will not grow back, so it diligently sharpens its tusks on river rocks after the end of a battle.'),
	('Haxorus', 180, 105500, 'Its tusks are incredibly destructive. They can easily slice through a thick, sturdy steel column every time.'),
	('Cubchoo', 50, 8500, 'Their snot is a barometer of health. When healthy, their snot is sticky and the power of their ice moves increases.'),
	('Beartic', 260, 260000, 'They love the cold seas of the north. They create pathways across the ocean waters by freezing their own breath.'),
	('Cryogonal', 110, 148000, 'They are composed of ice crystals. They capture prey with chains of ice, freezing the prey at -148° F.'),
	('Shelmet', 40, 7700, 'When it and Karrablast are together, and both receive electrical stimulation, they both evolve.'),
	('Accelgor', 80, 25300, 'When its body dries out, it weakens. So it wraps a membrane around itself for protection while it spits poison.'),
	('Stunfisk', 70, 11000, 'When its opponent can’t be paralyzed, it contorts itself with unexpected speed and flops away.'),
	('Mienfoo', 90, 20000, 'It takes pride in the speed at which it can use moves. What it loses in power, it makes up for in quantity.'),
	('Mienshao', 140, 35500, 'Using the long fur on its arms like whips, it launches into combo attacks that, once started, no one can stop.'),
	('Druddigon', 160, 139000, 'It runs through the narrow tunnels formed by Excadrill and Onix. It uses its sharp claws to catch prey.'),
	('Golett', 100, 92000, 'Ancient science fashioned this Pokémon from clay. It’s been active for thousands of years.'),
	('Golurk', 280, 330000, 'Golurk were created to protect people and Pokémon. They run on a mysterious energy.'),
	('Pawniard', 50, 10200, 'Ignoring their injuries, groups attack by sinking the blades that cover their bodies into their prey.'),
	('Bisharp', 160, 70000, 'This pitiless Pokémon commands a group of Pawniard to hound prey into immobility. It then moves in to finish the prey off.'),
	('Bouffalant', 160, 94600, 'They are known to charge so wildly that if a train were to enter their territory, they would send it flying.'),
	('Rufflet', 50, 10500, 'It stands up to massive opponents, not out of courage, but out of recklessness. But that is how it gets stronger.'),
	('Braviary', 150, 41000, 'For the sake of its friends, this brave warrior of the sky will not stop battling, even if injured.'),
	('Vullaby', 50, 9000, 'Their wings are too tiny to allow them to fly. They guard their posteriors with bones that were gathered by Mandibuzz.'),
	('Mandibuzz', 120, 39500, 'They fly in circles around the sky. When they spot prey, they attack and carry it back to their nest with ease.'),
	('Heatmor', 140, 58000, 'It draws in air through its tail, transforms it into fire, and uses it like a tongue. It melts Durant and eats them.'),
	('Durant', 30, 33000, 'Individuals each play different roles in driving Heatmor, their natural predator, away from their colony.'),
	('Deino', 80, 17300, 'Lacking sight, it’s unaware of its surroundings, so it bumps into things and eats anything that moves.'),
	('Zweilous', 140, 50000, 'The two heads do not get along. Whichever head eats more than the other gets to be the leader.'),
	('Hydreigon', 180, 160000, 'It responds to movement by attacking. This scary, three-headed Pokémon devours everything in its path!'),
	('Larvesta', 110, 28800, 'Said to have been born from the sun, it spews fire from its horns and encases itself in a cocoon of fire when it evolves.'),
	('Volcarona', 160, 46000, 'Thought to be an embodiment of the sun, it appeared during a bitterly cold winter and saved Pokémon from freezing.'),
	('Cobalion', 210, 250000, 'It has a body and heart of steel. It worked with its allies to punish people when they hurt Pokémon.'),
	('Terrakion', 190, 260000, 'Spoken of in legend, this Pokémon used its phenomenal power to destroy a castle in its effort to protect Pokémon.'),
	('Virizion', 200, 200000, 'Legends say this Pokémon confounded opponents with its swift movements.'),
	('Tornadus', 150, 63000, 'In every direction it flies, creating winds so powerful, they blow everything away.'),
	('Thundurus', 150, 61000, 'As it flies around, it shoots lightning all over the place and causes forest fires. It is therefore disliked.'),
	('Reshiram', 320, 330000, 'This legendary Pokémon can scorch the world with fire. It helps those who want to build a world of truth.'),
	('Zekrom', 290, 345000, 'This legendary Pokémon can scorch the world with lightning. It assists those who want to build an ideal world.'),
	('Landorus', 150, 68000, 'From the forces of lightning and wind, it creates energy to give nutrients to the soil and make the land abundant.'),
	('Kyurem', 300, 325000, 'This legendary ice Pokémon waits for a hero to fill in the missing parts of its body with truth or ideals.'),
	('Keldeo', 140, 48500, 'When it is resolute, its body fills with power and it becomes swifter. Its jumps are then too fast to follow.'),
	('Meloetta', 60, 6500, 'The melodies sung by Meloetta have the power to make Pokémon that hear them happy or sad.'),
	('Genesect', 150, 82500, 'This Pokémon existed 300 million years ago. Team Plasma altered it and attached a cannon to its back.')
;

INSERT INTO pokemon_type
    (type_name)
VALUES
     ('Fighting'), ('Rock'), ('Psychic'), ('Normal'), ('Ghost'),
     ('Dragon'), ('Fire'), ('Dark'), ('Electric'), ('Bug'), ('Ice'),
     ('Water'), ('Grass'), ('Steel'), ('Poison'), ('Ground'), ('Flying')
;

INSERT INTO type_assignment
    (pokemon_id, type_id)
VALUES
    (1, 13), (1, 15), (2, 13), (2, 15), (3, 13), (3, 15), (4, 7), (5, 7), (6, 7), (6, 17),
    (7, 12), (8, 12), (9, 12), (10, 10), (11, 10), (12, 10), (12, 17), (13, 10), (13, 15), (14, 10),
    (14, 15), (15, 10), (15, 15), (16, 4), (16, 17), (17, 4), (17, 17), (18, 4), (18, 17), (19, 4),
    (20, 4), (21, 4), (21, 17), (22, 4), (22, 17), (23, 15), (24, 15), (25, 9), (26, 9), (27, 16),
    (28, 16), (29, 15), (30, 15), (31, 15), (31, 16), (32, 15), (33, 15), (34, 15), (34, 16), (35, 4),
    (36, 4), (37, 7), (38, 7), (39, 4), (40, 4), (41, 15), (41, 17), (42, 15), (42, 17), (43, 13),
    (43, 15), (44, 13), (44, 15), (45, 13), (45, 15), (46, 10), (46, 13), (47, 10), (47, 13), (48, 10),
    (48, 15), (49, 10), (49, 15), (50, 16), (51, 16), (52, 4), (53, 4), (54, 12), (55, 12), (56, 1),
    (57, 1), (58, 7), (59, 7), (60, 12), (61, 12), (62, 12), (62, 1), (63, 3), (64, 3), (65, 3),
    (66, 1), (67, 1), (68, 1), (69, 13), (69, 15), (70, 13), (70, 15), (71, 13), (71, 15), (72, 12),
    (72, 15), (73, 12), (73, 15), (74, 2), (74, 16), (75, 2), (75, 16), (76, 2), (76, 16), (77, 7),
    (78, 7), (79, 12), (79, 3), (80, 12), (80, 3), (81, 9), (81, 14), (82, 9), (82, 14), (83, 4),
    (83, 17), (84, 4), (84, 17), (85, 4), (85, 17), (86, 12), (87, 12), (87, 11), (88, 15), (89, 15),
    (90, 12), (91, 12), (91, 11), (92, 5), (92, 15), (93, 5), (93, 15), (94, 5), (94, 15), (95, 2),
    (95, 16), (96, 3), (97, 3), (98, 12), (99, 12), (100, 9), (101, 9), (102, 13), (102, 3), (103, 13),
    (103, 3), (104, 16), (105, 16), (106, 1), (107, 1), (108, 4), (109, 15), (110, 15), (111, 16), (111, 2),
    (112, 16), (112, 2), (113, 4), (114, 13), (115, 4), (116, 12), (117, 12), (118, 12), (119, 12), (120, 12),
    (121, 12), (121, 3), (122, 3), (123, 10), (123, 17), (124, 11), (124, 3), (125, 9), (126, 7), (127, 10),
    (128, 4), (129, 12), (130, 12), (130, 17), (131, 12), (131, 11), (132, 4), (133, 4), (134, 12), (135, 9),
    (136, 7), (137, 4), (138, 2), (138, 12), (139, 2), (139, 12), (140, 2), (140, 12), (141, 2), (141, 12),
    (142, 2), (142, 17), (143, 4), (144, 11), (144, 17), (145, 9), (145, 17), (146, 7), (146, 17), (147, 6),
    (148, 6), (149, 6), (149, 17), (150, 3), (151, 3), (152, 13), (153, 13), (154, 13), (155, 7), (156, 7),
    (157, 7), (158, 12), (159, 12), (160, 12), (161, 4), (162, 4), (163, 4), (163, 17), (164, 4), (164, 17),
    (165, 10), (165, 17), (166, 10), (166, 17), (167, 10), (167, 15), (168, 10), (168, 15), (169, 15), (169, 17),
    (170, 12), (170, 9), (171, 12), (171, 9), (172, 9), (173, 4), (174, 4), (175, 4), (176, 4), (176, 17),
    (177, 3), (177, 17), (178, 3), (178, 17), (179, 9), (180, 9), (181, 9), (182, 13), (183, 12), (184, 12),
    (185, 2), (186, 12), (187, 13), (187, 17), (188, 13), (188, 17), (189, 13), (189, 17), (190, 4), (191, 13),
    (192, 13), (193, 10), (193, 17), (194, 12), (194, 16), (195, 12), (195, 16), (196, 3), (197, 8), (198, 8),
    (198, 17), (199, 12), (199, 3), (200, 5), (201, 3), (202, 3), (203, 4), (203, 3), (204, 10), (205, 10),
    (205, 14), (206, 4), (207, 16), (207, 17), (208, 14), (208, 16), (209, 4), (210, 4), (211, 12), (211, 15),
    (212, 10), (212, 14), (213, 10), (213, 2), (214, 10), (214, 1), (215, 8), (215, 11), (216, 4), (217, 4),
    (218, 7), (219, 7), (219, 2), (220, 11), (220, 16), (221, 11), (221, 16), (222, 12), (222, 2), (223, 12),
    (224, 12), (225, 11), (225, 17), (226, 12), (226, 17), (227, 14), (227, 17), (228, 8), (228, 7), (229, 8),
    (229, 7), (230, 12), (230, 6), (231, 16), (232, 16), (233, 4), (234, 4), (235, 4), (236, 1), (237, 1),
    (238, 11), (238, 3), (239, 9), (240, 7), (241, 4), (242, 4), (243, 9), (244, 7), (245, 12), (246, 2),
    (246, 16), (247, 2), (247, 16), (248, 2), (248, 8), (249, 3), (249, 17), (250, 7), (250, 17), (251, 3),
    (251, 13), (252, 13), (253, 13), (254, 13), (255, 7), (256, 7), (256, 1), (257, 7), (257, 1), (258, 12),
    (259, 12), (259, 16), (260, 12), (260, 16), (261, 8), (262, 8), (263, 4), (264, 4), (265, 10), (266, 10),
    (267, 10), (267, 17), (268, 10), (269, 10), (269, 15), (270, 12), (270, 13), (271, 12), (271, 13), (272, 12),
    (272, 13), (273, 13), (274, 13), (274, 8), (275, 13), (275, 8), (276, 4), (276, 17), (277, 4), (277, 17),
    (278, 12), (278, 17), (279, 12), (279, 17), (280, 3), (281, 3), (282, 3), (283, 10), (283, 12), (284, 10),
    (284, 17), (285, 13), (286, 13), (286, 1), (287, 4), (288, 4), (289, 4), (290, 10), (290, 16), (291, 10),
    (291, 17), (292, 10), (292, 5), (293, 4), (294, 4), (295, 4), (296, 1), (297, 1), (298, 4), (299, 2),
    (300, 4), (301, 4), (302, 8), (302, 5), (303, 14), (304, 14), (304, 2), (305, 14), (305, 2), (306, 14),
    (306, 2), (307, 1), (307, 3), (308, 1), (308, 3), (309, 9), (310, 9), (311, 9), (312, 9), (313, 10),
    (314, 10), (315, 13), (315, 15), (316, 15), (317, 15), (318, 12), (318, 8), (319, 12), (319, 8), (320, 12),
    (321, 12), (322, 7), (322, 16), (323, 7), (323, 16), (324, 7), (325, 3), (326, 3), (327, 4), (328, 16),
    (329, 16), (329, 6), (330, 16), (330, 6), (331, 13), (332, 13), (332, 8), (333, 4), (333, 17), (334, 6),
    (334, 17), (335, 4), (336, 15), (337, 2), (337, 3), (338, 2), (338, 3), (339, 12), (339, 16), (340, 12),
    (340, 16), (341, 12), (342, 12), (342, 8), (343, 16), (343, 3), (344, 16), (344, 3), (345, 2), (345, 13),
    (346, 2), (346, 13), (347, 2), (347, 10), (348, 2), (348, 10), (349, 12), (350, 12), (351, 4), (352, 4),
    (353, 5), (354, 5), (355, 5), (356, 5), (357, 13), (357, 17), (358, 3), (359, 8), (360, 3), (361, 11),
    (362, 11), (363, 11), (363, 12), (364, 11), (364, 12), (365, 11), (365, 12), (366, 12), (367, 12), (368, 12),
    (369, 12), (369, 2), (370, 12), (371, 6), (372, 6), (373, 6), (373, 17), (374, 14), (374, 3), (375, 14),
    (375, 3), (376, 14), (376, 3), (377, 2), (378, 11), (379, 14), (380, 6), (380, 3), (381, 6), (381, 3),
    (382, 12), (383, 16), (384, 6), (384, 17), (385, 14), (385, 3), (386, 3), (387, 13), (388, 13), (389, 13),
    (389, 16), (390, 7), (391, 7), (391, 1), (392, 7), (392, 1), (393, 12), (394, 12), (395, 12), (395, 14),
    (396, 4), (396, 17), (397, 4), (397, 17), (398, 4), (398, 17), (399, 4), (400, 4), (400, 12), (401, 10),
    (402, 10), (403, 9), (404, 9), (405, 9), (406, 13), (406, 15), (407, 13), (407, 15), (408, 2), (409, 2),
    (410, 2), (410, 14), (411, 2), (411, 14), (412, 10), (413, 10), (413, 13), (414, 10), (414, 17), (415, 10),
    (415, 17), (416, 10), (416, 17), (417, 9), (418, 12), (419, 12), (420, 13), (421, 13), (422, 12), (423, 12),
    (423, 16), (424, 4), (425, 5), (425, 17), (426, 5), (426, 17), (427, 4), (428, 4), (429, 5), (430, 8),
    (430, 17), (431, 4), (432, 4), (433, 3), (434, 15), (434, 8), (435, 15), (435, 8), (436, 14), (436, 3),
    (437, 14), (437, 3), (438, 2), (439, 3), (440, 4), (441, 4), (441, 17), (442, 5), (442, 8), (443, 6),
    (443, 16), (444, 6), (444, 16), (445, 6), (445, 16), (446, 4), (447, 1), (448, 1), (448, 14), (449, 16),
    (450, 16), (451, 15), (451, 10), (452, 15), (452, 8), (453, 15), (453, 1), (454, 15), (454, 1), (455, 13),
    (456, 12), (457, 12), (458, 12), (458, 17), (459, 13), (459, 11), (460, 13), (460, 11), (461, 8), (461, 11),
    (462, 9), (462, 14), (463, 4), (464, 16), (464, 2), (465, 13), (466, 9), (467, 7), (468, 4), (468, 17),
    (469, 10), (469, 17), (470, 13), (471, 11), (472, 16), (472, 17), (473, 11), (473, 16), (474, 4), (475, 3),
    (475, 1), (476, 2), (476, 14), (477, 5), (478, 11), (478, 5), (479, 9), (479, 5), (480, 3), (481, 3),
    (482, 3), (483, 14), (483, 6), (484, 12), (484, 6), (485, 7), (485, 14), (486, 4), (487, 5), (487, 6),
    (488, 3), (489, 12), (490, 12), (491, 8), (492, 13), (493, 4), (494, 3), (494, 7), (495, 13), (496, 13),
    (497, 13), (498, 7), (499, 7), (499, 1), (500, 7), (500, 1), (501, 12), (502, 12), (503, 12), (504, 4),
    (505, 4), (506, 4), (507, 4), (508, 4), (509, 8), (510, 8), (511, 13), (512, 13), (513, 7), (514, 7),
    (515, 12), (516, 12), (517, 3), (518, 3), (519, 4), (519, 17), (520, 4), (520, 17), (521, 4), (521, 17),
    (522, 9), (523, 9), (524, 2), (525, 2), (526, 2), (527, 3), (527, 17), (528, 3), (528, 17), (529, 16),
    (530, 16), (530, 14), (531, 4), (532, 1), (533, 1), (534, 1), (535, 12), (536, 12), (536, 16), (537, 12),
    (537, 16), (538, 1), (539, 1), (540, 10), (540, 13), (541, 10), (541, 13), (542, 10), (542, 13), (543, 10),
    (543, 15), (544, 10), (544, 15), (545, 10), (545, 15), (546, 13), (547, 13), (548, 13), (549, 13), (550, 12),
    (551, 16), (551, 8), (552, 16), (552, 8), (553, 16), (553, 8), (554, 7), (555, 7), (556, 13), (557, 10),
    (557, 2), (558, 10), (558, 2), (559, 8), (559, 1), (560, 8), (560, 1), (561, 3), (561, 17), (562, 5),
    (563, 5), (564, 12), (564, 2), (565, 12), (565, 2), (566, 2), (566, 17), (567, 2), (567, 17), (568, 15),
    (569, 15), (570, 8), (571, 8), (572, 4), (573, 4), (574, 3), (575, 3), (576, 3), (577, 3), (578, 3),
    (579, 3), (580, 12), (580, 17), (581, 12), (581, 17), (582, 11), (583, 11), (584, 11), (585, 4), (585, 13),
    (586, 4), (586, 13), (587, 9), (587, 17), (588, 10), (589, 10), (589, 14), (590, 13), (590, 15), (591, 13),
    (591, 15), (592, 12), (592, 5), (593, 12), (593, 5), (594, 12), (595, 10), (595, 9), (596, 10), (596, 9),
    (597, 13), (597, 14), (598, 13), (598, 14), (599, 14), (600, 14), (601, 14), (602, 9), (603, 9), (604, 9),
    (605, 3), (606, 3), (607, 5), (607, 7), (608, 5), (608, 7), (609, 5), (609, 7), (610, 6), (611, 6),
    (612, 6), (613, 11), (614, 11), (615, 11), (616, 10), (617, 10), (618, 16), (618, 9), (619, 1), (620, 1),
    (621, 6), (622, 16), (622, 5), (623, 16), (623, 5), (624, 8), (624, 14), (625, 8), (625, 14), (626, 4),
    (627, 4), (627, 17), (628, 4), (628, 17), (629, 8), (629, 17), (630, 8), (630, 17), (631, 7), (632, 10),
    (632, 14), (633, 8), (633, 6), (634, 8), (634, 6), (635, 8), (635, 6), (636, 10), (636, 7), (637, 10),
    (637, 7), (638, 14), (638, 1), (639, 2), (639, 1), (640, 13), (640, 1), (641, 17), (642, 9), (642, 17),
    (643, 6), (643, 7), (644, 6), (644, 9), (645, 16), (645, 17), (646, 6), (646, 11), (647, 12), (647, 1),
    (648, 4), (648, 3), (649, 10), (649, 14)
