import pytest

from wednesday_2 import tail_swap


def test_basic_test_1():
    assert tail_swap(['abc:123', 'cde:456']) == ['abc:456', 'cde:123']


def test_basic_test_2():
    assert tail_swap(['a:12345', '777:xyz']) == ['a:xyz', '777:12345']


@pytest.mark.parametrize("a,b",
                         [(['1WToAV2h38:Z', 'cC:WA@'], ['1WToAV2h38:WA@', 'cC:Z']),
                          (['6%Bbl0QXN:#79Pfon', 'Lj!dzk:ZJ'],
                           ['6%Bbl0QXN:ZJ', 'Lj!dzk:#79Pfon']),
                             (['xm:cn', 'D9d1:SdcXyMG9'],
                              ['xm:SdcXyMG9', 'D9d1:cn']),
                             (['sy@P_2HS:L&@W%i', 'Kowe:lBZof'],
                              ['sy@P_2HS:lBZof', 'Kowe:L&@W%i']),
                             (['$D!0Q6l:RRSKzB', 'h:zGz3l'],
                              ['$D!0Q6l:zGz3l', 'h:RRSKzB']),
                             (['Wnv6_Tpa8x:p&ssT', 'iE:HyQapqOo'],
                              ['Wnv6_Tpa8x:HyQapqOo', 'iE:p&ssT']),
                             (['nTDFYP:*KeXqOq', 'F:cRFmsDHGP'],
                              ['nTDFYP:cRFmsDHGP', 'F:*KeXqOq']),
                             (['d!CeB^n$ex:0W0C', 'KR_AY:7RL%T!i!m'],
                              ['d!CeB^n$ex:7RL%T!i!m', 'KR_AY:0W0C']),
                             (['pqi:7vK!9PZnjA', '*2Ll0WJKj:Ero'],
                              ['pqi:Ero', '*2Ll0WJKj:7vK!9PZnjA']),
                             (['MuAa5NO:@NI', 'PG_dzGB:FGi@'],
                              ['MuAa5NO:FGi@', 'PG_dzGB:@NI']),
                             (['$X0UUL_MD0:JGJoZMpS', 'j:LHJgzNhcv'],
                              ['$X0UUL_MD0:LHJgzNhcv', 'j:JGJoZMpS']),
                             (['lem:CUxMnIzCQ', '5F$31Twt:zC52'],
                              ['lem:zC52', '5F$31Twt:CUxMnIzCQ']),
                             (['krIp5HQPE:5t*', 'YLS6Nw3_:rS'],
                              ['krIp5HQPE:rS', 'YLS6Nw3_:5t*']),
                             (['s:H', '72mz7s0bn:7'], ['s:7', '72mz7s0bn:H']),
                             (['zTLDVSK:NPU4', '$*_SE:CwEYAjn#R'],
                              ['zTLDVSK:CwEYAjn#R', '$*_SE:NPU4']),
                             (['KBb0@TKt:RyXe1K^K', 'y*#Tec:NNCWv_QQ8'],
                              ['KBb0@TKt:NNCWv_QQ8', 'y*#Tec:RyXe1K^K']),
                             (['Zpjx!$Z:pZw', 'g:T'], ['Zpjx!$Z:T', 'g:pZw']),
                             (['O2I&Sr:@1K1', 'U9$IzF^rs:NociP#ql&'],
                              ['O2I&Sr:NociP#ql&', 'U9$IzF^rs:@1K1']),
                             (['o44z:7NPgGVQ&54', 'BOATO0:bc@OM4'],
                              ['o44z:bc@OM4', 'BOATO0:7NPgGVQ&54']),
                             (['6nXi7CpZqd:Jjx', 'm^rPXXuu0:V'],
                              ['6nXi7CpZqd:V', 'm^rPXXuu0:Jjx']),
                             (['I:ca#Nw', 'OE:6TE'], ['I:6TE', 'OE:ca#Nw']),
                             (['9H1%myIc:pZuo', 't4*Hkw$NMu:ck*zVAR'],
                              ['9H1%myIc:ck*zVAR', 't4*Hkw$NMu:pZuo']),
                             (['$NldU3:B15VKg#Ot', 't_MJvc:&3CVYO'],
                              ['$NldU3:&3CVYO', 't_MJvc:B15VKg#Ot']),
                             (['q2tlwm##I:xkEL', 'rkyurIW:JH9W4'],
                              ['q2tlwm##I:JH9W4', 'rkyurIW:xkEL']),
                             (['3:VscQSLKvKt', 'FVMAeg:UuVTR2R5'],
                              ['3:UuVTR2R5', 'FVMAeg:VscQSLKvKt']),
                             (['5s^Fv:QuW', 'Tw@:7s*YX4t!S'],
                              ['5s^Fv:7s*YX4t!S', 'Tw@:QuW']),
                             (['1:cDmgVoQu', 'c:*^QD'], ['1:*^QD', 'c:cDmgVoQu']),
                             (['G:uQ2M9', '#:l5XpZ#'], ['G:l5XpZ#', '#:uQ2M9']),
                             (['6aEHT2#w8:y9', '#fTkj2k$t:WaQ5bk%Kw6'],
                              ['6aEHT2#w8:WaQ5bk%Kw6', '#fTkj2k$t:y9']),
                             (['7l:dWQvXO', 'OZR2$eIfM:N2c'],
                              ['7l:N2c', 'OZR2$eIfM:dWQvXO']),
                             (['ee:fgTadvN', 'hAKqnX:Qy1@omLN*'],
                              ['ee:Qy1@omLN*', 'hAKqnX:fgTadvN']),
                             (['qc8H:%6HUS&!5j', 'AxZPWNp*7:Rtgrx02V'],
                              ['qc8H:Rtgrx02V', 'AxZPWNp*7:%6HUS&!5j']),
                             (['QqKkT:hatl', '$6c4!4:BrnS'],
                              ['QqKkT:BrnS', '$6c4!4:hatl']),
                             (['8P7VxlESd:J$', 'i1Bw:yGb2jQ'],
                              ['8P7VxlESd:yGb2jQ', 'i1Bw:J$']),
                             (['Fhsy:9Q0yOq_', 'LfWnUCs0pl:xP'],
                              ['Fhsy:xP', 'LfWnUCs0pl:9Q0yOq_']),
                             (['##v_:mY!B&Q', '@:rWgJI#'],
                              ['##v_:rWgJI#', '@:mY!B&Q']),
                             (['S*cCT*4D3:y9OYahy', '3R@k:U'],
                              ['S*cCT*4D3:U', '3R@k:y9OYahy']),
                             (['wv:gD', 'U#h:P3w'], ['wv:P3w', 'U#h:gD']),
                             (['z$G2LKbi:_QHjq', '^dub3L4cYh:1ordrQL8R'],
                              ['z$G2LKbi:1ordrQL8R', '^dub3L4cYh:_QHjq']),
                             (['8:U8^lr', '@YO%bu3c3e:hlISyr2'],
                              ['8:hlISyr2', '@YO%bu3c3e:U8^lr']),
                             (['0sMPmKIFXy:8Gr4', 'm:36&'],
                              ['0sMPmKIFXy:36&', 'm:8Gr4']),
                             (['I%AGfS3$kr:kdBb^', 'K#@AFwX9:FYx#wyHn'],
                              ['I%AGfS3$kr:FYx#wyHn', 'K#@AFwX9:kdBb^']),
                             (['O:E3THAgHvS%', 'H5uW!ep3O^:f4'],
                              ['O:f4', 'H5uW!ep3O^:E3THAgHvS%']),
                             (['dZxpl2_gr:flj@K53Gt', '#6NATgl8:$'],
                              ['dZxpl2_gr:$', '#6NATgl8:flj@K53Gt']),
                             (['yQUhCHi:JK72X', '@gJ:JHVrqhk'],
                              ['yQUhCHi:JHVrqhk', '@gJ:JK72X']),
                             (['VJwQ63CS*8:WH', 'iK8vRK7d:rS'],
                              ['VJwQ63CS*8:rS', 'iK8vRK7d:WH']),
                             (['D4%I6Ikw#:pGA%', 'P:RdfE*R'],
                              ['D4%I6Ikw#:RdfE*R', 'P:pGA%']),
                             (['GvQ:o', 'o%:LeaheCo%oy'],
                              ['GvQ:LeaheCo%oy', 'o%:o']),
                             (['Cz*MUAy:Bn5k4Je', '9Lf:HfiY'],
                              ['Cz*MUAy:HfiY', '9Lf:Bn5k4Je']),
                             (['ySxoL01:6z', '*xpQRR:qp%C%Q#*u'],
                              ['ySxoL01:qp%C%Q#*u', '*xpQRR:6z']),
                             (['R1:rdPo^O#', 'Wvm1:O0LL#A%Zv'],
                              ['R1:O0LL#A%Zv', 'Wvm1:rdPo^O#']),
                             (['cx:!', 'K^ugAOvu@:%I4iGPlk'],
                              ['cx:%I4iGPlk', 'K^ugAOvu@:!']),
                             (['R$11bl@A8:uNex', '0F3fDe:n*94$&ip'],
                              ['R$11bl@A8:n*94$&ip', '0F3fDe:uNex']),
                             (['!YwNCaG:5A', 'A!6lq5EpX:91L'],
                              ['!YwNCaG:91L', 'A!6lq5EpX:5A']),
                             (['gtu^8ewjw:Wg^*3', '^mxU:U'],
                              ['gtu^8ewjw:U', '^mxU:Wg^*3']),
                             (['P:5Yk0Mu$R3', '$4AOeLEMgP:*o1'],
                              ['P:*o1', '$4AOeLEMgP:5Yk0Mu$R3']),
                             (['Q3XFO5C:V4PC0NM', 'H%VeSY:yCV'],
                              ['Q3XFO5C:yCV', 'H%VeSY:V4PC0NM']),
                             (['Xyw&V:vz3l$Ir8', 'lwGXmlPrHh:T5b$GD'],
                              ['Xyw&V:T5b$GD', 'lwGXmlPrHh:vz3l$Ir8']),
                             (['PzYUmKc*U^:hVp&UEFB%', '$m*WZ6:&'],
                              ['PzYUmKc*U^:&', '$m*WZ6:hVp&UEFB%']),
                             (['fJj6X96:kCSCu6L', '*tp1ddiXS:C@&kTgke'],
                              ['fJj6X96:C@&kTgke', '*tp1ddiXS:kCSCu6L']),
                             (['^bJy9W8c:aLumuGdY', 'b:2JrWN9B&'],
                              ['^bJy9W8c:2JrWN9B&', 'b:aLumuGdY']),
                             (['L:_IeFi3', 'i8lrvO&P:#'],
                              ['L:#', 'i8lrvO&P:_IeFi3']),
                             (['c6DUT:nMNqS8sK', 'WWLTg:t'],
                              ['c6DUT:t', 'WWLTg:nMNqS8sK']),
                             (['#5DA7V@U:nDVT8hh4', 'pLUjJnNFT*:8p#^bA'],
                              ['#5DA7V@U:8p#^bA', 'pLUjJnNFT*:nDVT8hh4']),
                             (['h9ipPj@k:DdlkK6L3', 'J8cV%H:FIk!d'],
                              ['h9ipPj@k:FIk!d', 'J8cV%H:DdlkK6L3']),
                             (['d9%!0:FmKwFV', 'f*b!PXs58*:l1kkS'],
                              ['d9%!0:l1kkS', 'f*b!PXs58*:FmKwFV']),
                             (['eXv%3X6d^:a6!0fki3', 'FIHB8:#axAqwhO'],
                              ['eXv%3X6d^:#axAqwhO', 'FIHB8:a6!0fki3']),
                             (['HEm:S', '#S&F:tD&ioSpHjh'],
                              ['HEm:tD&ioSpHjh', '#S&F:S']),
                             (['6jh:CyD$MwO1d', 'l6Ch_Is$Ol:&uW86*g$K'],
                              ['6jh:&uW86*g$K', 'l6Ch_Is$Ol:CyD$MwO1d']),
                             (['#FXwUM:z', '!aD8giY:ZfuGon9%8'],
                              ['#FXwUM:ZfuGon9%8', '!aD8giY:z']),
                             (['KHDL:6KDjBRy', '^bvQbpt4Y:4ub9'],
                              ['KHDL:4ub9', '^bvQbpt4Y:6KDjBRy']),
                             (['gTo3:IaELD', 'fjqqF9:Bah%$Jn'],
                              ['gTo3:Bah%$Jn', 'fjqqF9:IaELD']),
                             (['OiIs:A^QPNP', 'm84gSA:B!%7'],
                              ['OiIs:B!%7', 'm84gSA:A^QPNP']),
                             (['q#:aRrpVAls2', '&zPD_:K^Fas'],
                              ['q#:K^Fas', '&zPD_:aRrpVAls2']),
                             (['JT#uk:xq5e1klpt', '4GCRJ:28jqFFlir'],
                              ['JT#uk:28jqFFlir', '4GCRJ:xq5e1klpt']),
                             (['HSDx%tYmP:jjIMQm', '7kk9&hqUaU:Sc'],
                              ['HSDx%tYmP:Sc', '7kk9&hqUaU:jjIMQm']),
                             (['H*$MmQyDc:KdEme3', '!*%mQHVB*y:bk*yR!yE'],
                              ['H*$MmQyDc:bk*yR!yE', '!*%mQHVB*y:KdEme3']),
                             (['&x:SGsq2LLat', 'nN4O2k9:OIfzGm3J9'],
                              ['&x:OIfzGm3J9', 'nN4O2k9:SGsq2LLat']),
                             (['j*6sv6oB:7Ifd&*FH', 'TOUTqHLp:p_i'],
                              ['j*6sv6oB:p_i', 'TOUTqHLp:7Ifd&*FH']),
                             (['zs%2m:jrvEWZ', '0:$ob'],
                              ['zs%2m:$ob', '0:jrvEWZ']),
                             (['n*r@I4kt:Be', 'M0vG:AM'],
                              ['n*r@I4kt:AM', 'M0vG:Be']),
                             (['HLjP:gjO5@^g', 'Psho14h:XaZCK'],
                              ['HLjP:XaZCK', 'Psho14h:gjO5@^g']),
                             (['7EI1Kv$d!:T', 'XM5*5&ryM:Sir6*Fr'],
                              ['7EI1Kv$d!:Sir6*Fr', 'XM5*5&ryM:T']),
                             (['oor5:xPW', '&$:Ba1yU%5O'],
                              ['oor5:Ba1yU%5O', '&$:xPW']),
                             (['I_!n:jzoWTPL', 'lO:vevTYxcIsb'],
                              ['I_!n:vevTYxcIsb', 'lO:jzoWTPL']),
                             (['iGYzx:^8M', 'F%r8@O:AHae'],
                              ['iGYzx:AHae', 'F%r8@O:^8M']),
                             (['K$:VIWjK!', 'u:Q'], ['K$:Q', 'u:VIWjK!']),
                             (['Wlv7:_Do', '0gAK8:lhsf@9'],
                              ['Wlv7:lhsf@9', '0gAK8:_Do']),
                             (['T:@_!45', '&T:8Whf6ppok'],
                              ['T:8Whf6ppok', '&T:@_!45']),
                             (['tFML3J:47nBZrQP17', 'eR:R'],
                              ['tFML3J:R', 'eR:47nBZrQP17']),
                             (['@B!!G:!qO', 'oYx7q:h'], ['@B!!G:h', 'oYx7q:!qO']),
                             (['2%be#qOdB:N1HfcXv', 'n1rb2_V6%:BHma$YjhE'],
                              ['2%be#qOdB:BHma$YjhE', 'n1rb2_V6%:N1HfcXv']),
                             (['ioa%7*eR:g0', 'D:$N%yrn7qt'],
                              ['ioa%7*eR:$N%yrn7qt', 'D:g0']),
                             (['LyF:fLr', 'VJ$I:L'], ['LyF:L', 'VJ$I:fLr']),
                             (['s0Lh3IC@:7X5svYSS', '^l0y:F'],
                              ['s0Lh3IC@:F', '^l0y:7X5svYSS']),
                             (['QE:jBLA5Zl', 'o*4l99^:_PaiO*'],
                              ['QE:_PaiO*', 'o*4l99^:jBLA5Zl']),
                             (['T:XbpRP', '3:^WXu0%'], ['T:^WXu0%', '3:XbpRP']),
                             (['F^K%qLk:M7lZoEY', 'U2S:WlT'],
                              ['F^K%qLk:WlT', 'U2S:M7lZoEY']),
                             (['XhH7k:%iGnF', 'L8:!'], ['XhH7k:!', 'L8:%iGnF']),
                             (['ZETNx%j:$taiU85%L', 'IOHqfLwXT:qS'], ['ZETNx%j:qS', 'IOHqfLwXT:$taiU85%L'])])
def test_random_test_cases(a, b):
    assert tail_swap(a) == b
